name: toto

services:
  user-service:
    image: totocorpsoftwareinc/user-service:${USER_SERVICE_TAG}
    container_name: user-service
    restart: on-failure:5
    networks:
      - corp-network
    ports:
      - "5432"
    environment:
      # https://docs.docker.com/compose/environment-variables/set-environment-variables/#compose-file
      - ENV_DATABASE_PASSWORD=${ENV_DATABASE_PASSWORD}

  user-dashboard:
    image: totocorpsoftwareinc/user-dashboard:${USER_DASHBOARD_TAG}
    container_name: user-dashboard
    restart: on-failure:5
    networks:
      - corp-network
    environment:
      - ORIGIN=${USER_DASHBOARD_ORIGIN:-http://admin.localhost}

  webserver:
    image: totocorpsoftwareinc/webserver:${WEBSERVER_TAG}
    container_name: webserver
    restart: on-failure:5
    networks:
      - corp-network
    environment:
      - ORIGIN=${WEBSERVER_ORIGIN:-http://admin.localhost}

  # https://www.reddit.com/r/Traefik/comments/123oz36/traefik_dashboard_access_with_staticdynamic/
  reverse-proxy:
    image: traefik:v3.0
    container_name: reverse-proxy
    restart: always
    networks:
      - corp-network
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TRAEFIK_USER=${TRAEFIK_USER}
      - TRAEFIK_HASHED_PASSWORD=${TRAEFIK_HASHED_PASSWORD}
    volumes:
      # https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config/:/etc/traefik/config/
      - /var/run/docker.sock:/var/run/docker.sock
      # https://doc.traefik.io/traefik/https/acme/#storage
      - /etc/certificates:/etc/certificates/

# https://docs.docker.com/compose/compose-file/06-networks/
networks:
  corp-network:
