api:
  dashboard: true
  # https://doc.traefik.io/traefik/operations/dashboard/#insecure-mode
  insecure: false

# https://doc.traefik.io/traefik/observability/logs/#level
log:
  level: DEBUG

# https://doc.traefik.io/traefik/observability/access-logs/#configuration
accesslog:
  addInternals: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":443"

providers:
  # https://doc.traefik.io/traefik/providers/file/#directory
  file:
    directory: "/etc/traefik/config"

# https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/
certificatesResolvers:
  letsencryptresolver:
    acme:
      # https://doc.traefik.io/traefik/v2.3/getting-started/configuration-overview/#the-static-configuration
      # We need to replace this when generating the file.
      email: ${EMAIL_TO_BE_REPLACED}
      storage: "acme.json"
      tlsChallenge: {}
