version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/frontend/galactic-sovereign-frontend"
      - "/frontend/user-dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "all"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "all"
