// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_managing_universes.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_managing_universes.go -destination=drivenadapterstest/mocks.go -package=drivenadapterstest
//

// Package drivenadapterstest is a generated GoMock package.
package drivenadapterstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingUniverses is a mock of ForManagingUniverses interface.
type MockForManagingUniverses struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingUniversesMockRecorder
	isgomock struct{}
}

// MockForManagingUniversesMockRecorder is the mock recorder for MockForManagingUniverses.
type MockForManagingUniversesMockRecorder struct {
	mock *MockForManagingUniverses
}

// NewMockForManagingUniverses creates a new mock instance.
func NewMockForManagingUniverses(ctrl *gomock.Controller) *MockForManagingUniverses {
	mock := &MockForManagingUniverses{ctrl: ctrl}
	mock.recorder = &MockForManagingUniversesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingUniverses) EXPECT() *MockForManagingUniversesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForManagingUniverses) Create(ctx context.Context, universe models.Universe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, universe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockForManagingUniversesMockRecorder) Create(ctx, universe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForManagingUniverses)(nil).Create), ctx, universe)
}

// Delete mocks base method.
func (m *MockForManagingUniverses) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingUniversesMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingUniverses)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockForManagingUniverses) Get(ctx context.Context, id uuid.UUID) (models.Universe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Universe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForManagingUniversesMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForManagingUniverses)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockForManagingUniverses) List(ctx context.Context) ([]models.Universe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Universe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForManagingUniversesMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForManagingUniverses)(nil).List), ctx)
}
