// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_listing_buildings.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_listing_buildings.go -destination=drivenportstest/buildings_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForFetchingBuilding is a mock of ForFetchingBuilding interface.
type MockForFetchingBuilding struct {
	ctrl     *gomock.Controller
	recorder *MockForFetchingBuildingMockRecorder
	isgomock struct{}
}

// MockForFetchingBuildingMockRecorder is the mock recorder for MockForFetchingBuilding.
type MockForFetchingBuildingMockRecorder struct {
	mock *MockForFetchingBuilding
}

// NewMockForFetchingBuilding creates a new mock instance.
func NewMockForFetchingBuilding(ctrl *gomock.Controller) *MockForFetchingBuilding {
	mock := &MockForFetchingBuilding{ctrl: ctrl}
	mock.recorder = &MockForFetchingBuildingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForFetchingBuilding) EXPECT() *MockForFetchingBuildingMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockForFetchingBuilding) Get(ctx context.Context, id uuid.UUID) (models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForFetchingBuildingMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForFetchingBuilding)(nil).Get), ctx, id)
}
