// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_listing_buildings.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_listing_buildings.go -destination=drivenportstest/buildings_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForListingBuildings is a mock of ForListingBuildings interface.
type MockForListingBuildings struct {
	ctrl     *gomock.Controller
	recorder *MockForListingBuildingsMockRecorder
	isgomock struct{}
}

// MockForListingBuildingsMockRecorder is the mock recorder for MockForListingBuildings.
type MockForListingBuildingsMockRecorder struct {
	mock *MockForListingBuildings
}

// NewMockForListingBuildings creates a new mock instance.
func NewMockForListingBuildings(ctrl *gomock.Controller) *MockForListingBuildings {
	mock := &MockForListingBuildings{ctrl: ctrl}
	mock.recorder = &MockForListingBuildingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForListingBuildings) EXPECT() *MockForListingBuildingsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockForListingBuildings) Get(ctx context.Context, id uuid.UUID) (models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForListingBuildingsMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForListingBuildings)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockForListingBuildings) List(ctx context.Context) ([]models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForListingBuildingsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForListingBuildings)(nil).List), ctx)
}
