// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_managing_building_actions.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_managing_building_actions.go -destination=drivenportstest/building_actions_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingBuildingActions is a mock of ForManagingBuildingActions interface.
type MockForManagingBuildingActions struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingBuildingActionsMockRecorder
	isgomock struct{}
}

// MockForManagingBuildingActionsMockRecorder is the mock recorder for MockForManagingBuildingActions.
type MockForManagingBuildingActionsMockRecorder struct {
	mock *MockForManagingBuildingActions
}

// NewMockForManagingBuildingActions creates a new mock instance.
func NewMockForManagingBuildingActions(ctrl *gomock.Controller) *MockForManagingBuildingActions {
	mock := &MockForManagingBuildingActions{ctrl: ctrl}
	mock.recorder = &MockForManagingBuildingActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingBuildingActions) EXPECT() *MockForManagingBuildingActionsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForManagingBuildingActions) Create(ctx context.Context, planet models.Planet, action models.BuildingAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, planet, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockForManagingBuildingActionsMockRecorder) Create(ctx, planet, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForManagingBuildingActions)(nil).Create), ctx, planet, action)
}

// Delete mocks base method.
func (m *MockForManagingBuildingActions) Delete(ctx context.Context, planet models.Planet, action models.BuildingAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, planet, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingBuildingActionsMockRecorder) Delete(ctx, planet, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingBuildingActions)(nil).Delete), ctx, planet, action)
}

// Get mocks base method.
func (m *MockForManagingBuildingActions) Get(ctx context.Context, id uuid.UUID) (models.BuildingAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.BuildingAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForManagingBuildingActionsMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForManagingBuildingActions)(nil).Get), ctx, id)
}
