// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_creating_planets.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_creating_planets.go -destination=drivenportstest/create_planets_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	gomock "go.uber.org/mock/gomock"
)

// MockForCreatingPlanets is a mock of ForCreatingPlanets interface.
type MockForCreatingPlanets struct {
	ctrl     *gomock.Controller
	recorder *MockForCreatingPlanetsMockRecorder
	isgomock struct{}
}

// MockForCreatingPlanetsMockRecorder is the mock recorder for MockForCreatingPlanets.
type MockForCreatingPlanetsMockRecorder struct {
	mock *MockForCreatingPlanets
}

// NewMockForCreatingPlanets creates a new mock instance.
func NewMockForCreatingPlanets(ctrl *gomock.Controller) *MockForCreatingPlanets {
	mock := &MockForCreatingPlanets{ctrl: ctrl}
	mock.recorder = &MockForCreatingPlanetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCreatingPlanets) EXPECT() *MockForCreatingPlanetsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForCreatingPlanets) Create(ctx context.Context, planet models.Planet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, planet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockForCreatingPlanetsMockRecorder) Create(ctx, planet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForCreatingPlanets)(nil).Create), ctx, planet)
}
