// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_checking_database_connection.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_checking_database_connection.go -destination=drivenportstest/database_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockForCheckingDatabaseConnection is a mock of ForCheckingDatabaseConnection interface.
type MockForCheckingDatabaseConnection struct {
	ctrl     *gomock.Controller
	recorder *MockForCheckingDatabaseConnectionMockRecorder
	isgomock struct{}
}

// MockForCheckingDatabaseConnectionMockRecorder is the mock recorder for MockForCheckingDatabaseConnection.
type MockForCheckingDatabaseConnectionMockRecorder struct {
	mock *MockForCheckingDatabaseConnection
}

// NewMockForCheckingDatabaseConnection creates a new mock instance.
func NewMockForCheckingDatabaseConnection(ctrl *gomock.Controller) *MockForCheckingDatabaseConnection {
	mock := &MockForCheckingDatabaseConnection{ctrl: ctrl}
	mock.recorder = &MockForCheckingDatabaseConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCheckingDatabaseConnection) EXPECT() *MockForCheckingDatabaseConnectionMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockForCheckingDatabaseConnection) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockForCheckingDatabaseConnectionMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockForCheckingDatabaseConnection)(nil).Ping), ctx)
}
