// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_deleting_planet.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_deleting_planet.go -destination=drivenportstest/delete_planet_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	drivenports "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/ports/driven"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForFeletingPlanet is a mock of ForFeletingPlanet interface.
type MockForFeletingPlanet struct {
	ctrl     *gomock.Controller
	recorder *MockForFeletingPlanetMockRecorder
	isgomock struct{}
}

// MockForFeletingPlanetMockRecorder is the mock recorder for MockForFeletingPlanet.
type MockForFeletingPlanetMockRecorder struct {
	mock *MockForFeletingPlanet
}

// NewMockForFeletingPlanet creates a new mock instance.
func NewMockForFeletingPlanet(ctrl *gomock.Controller) *MockForFeletingPlanet {
	mock := &MockForFeletingPlanet{ctrl: ctrl}
	mock.recorder = &MockForFeletingPlanetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForFeletingPlanet) EXPECT() *MockForFeletingPlanetMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockForFeletingPlanet) Delete(ctx context.Context, id uuid.UUID, deleter drivenports.PlanetDeleter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, deleter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForFeletingPlanetMockRecorder) Delete(ctx, id, deleter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForFeletingPlanet)(nil).Delete), ctx, id, deleter)
}
