// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_dispatching_fleet.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_dispatching_fleet.go -destination=drivenportstest/dispatch_fleet_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	drivenports "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/ports/driven"
	gomock "go.uber.org/mock/gomock"
)

// MockForDispatchingFleet is a mock of ForDispatchingFleet interface.
type MockForDispatchingFleet struct {
	ctrl     *gomock.Controller
	recorder *MockForDispatchingFleetMockRecorder
	isgomock struct{}
}

// MockForDispatchingFleetMockRecorder is the mock recorder for MockForDispatchingFleet.
type MockForDispatchingFleetMockRecorder struct {
	mock *MockForDispatchingFleet
}

// NewMockForDispatchingFleet creates a new mock instance.
func NewMockForDispatchingFleet(ctrl *gomock.Controller) *MockForDispatchingFleet {
	mock := &MockForDispatchingFleet{ctrl: ctrl}
	mock.recorder = &MockForDispatchingFleetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForDispatchingFleet) EXPECT() *MockForDispatchingFleetMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockForDispatchingFleet) Dispatch(ctx context.Context, req request.FleetCreationRequest, mutator drivenports.FleetCreator) (models.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", ctx, req, mutator)
	ret0, _ := ret[0].(models.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockForDispatchingFleetMockRecorder) Dispatch(ctx, req, mutator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockForDispatchingFleet)(nil).Dispatch), ctx, req, mutator)
}
