// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_fetching_universes.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_fetching_universes.go -destination=drivenportstest/fetch_universes_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForFetchingUniverses is a mock of ForFetchingUniverses interface.
type MockForFetchingUniverses struct {
	ctrl     *gomock.Controller
	recorder *MockForFetchingUniversesMockRecorder
	isgomock struct{}
}

// MockForFetchingUniversesMockRecorder is the mock recorder for MockForFetchingUniverses.
type MockForFetchingUniversesMockRecorder struct {
	mock *MockForFetchingUniverses
}

// NewMockForFetchingUniverses creates a new mock instance.
func NewMockForFetchingUniverses(ctrl *gomock.Controller) *MockForFetchingUniverses {
	mock := &MockForFetchingUniverses{ctrl: ctrl}
	mock.recorder = &MockForFetchingUniversesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForFetchingUniverses) EXPECT() *MockForFetchingUniversesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockForFetchingUniverses) Get(ctx context.Context, id uuid.UUID) (models.Universe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Universe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForFetchingUniversesMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForFetchingUniverses)(nil).Get), ctx, id)
}

// GetByPlanetId mocks base method.
func (m *MockForFetchingUniverses) GetByPlanetId(ctx context.Context, planet uuid.UUID) (models.Universe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlanetId", ctx, planet)
	ret0, _ := ret[0].(models.Universe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPlanetId indicates an expected call of GetByPlanetId.
func (mr *MockForFetchingUniversesMockRecorder) GetByPlanetId(ctx, planet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPlanetId", reflect.TypeOf((*MockForFetchingUniverses)(nil).GetByPlanetId), ctx, planet)
}

// List mocks base method.
func (m *MockForFetchingUniverses) List(ctx context.Context) ([]models.Universe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Universe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForFetchingUniversesMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForFetchingUniverses)(nil).List), ctx)
}
