// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_managing_planets.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_managing_planets.go -destination=drivenportstest/planets_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingPlanets is a mock of ForManagingPlanets interface.
type MockForManagingPlanets struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingPlanetsMockRecorder
	isgomock struct{}
}

// MockForManagingPlanetsMockRecorder is the mock recorder for MockForManagingPlanets.
type MockForManagingPlanetsMockRecorder struct {
	mock *MockForManagingPlanets
}

// NewMockForManagingPlanets creates a new mock instance.
func NewMockForManagingPlanets(ctrl *gomock.Controller) *MockForManagingPlanets {
	mock := &MockForManagingPlanets{ctrl: ctrl}
	mock.recorder = &MockForManagingPlanetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingPlanets) EXPECT() *MockForManagingPlanetsMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockForManagingPlanets) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingPlanetsMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingPlanets)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockForManagingPlanets) Get(ctx context.Context, id uuid.UUID) (models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForManagingPlanetsMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForManagingPlanets)(nil).Get), ctx, id)
}

// GetByAction mocks base method.
func (m *MockForManagingPlanets) GetByAction(ctx context.Context, action uuid.UUID) (models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAction", ctx, action)
	ret0, _ := ret[0].(models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAction indicates an expected call of GetByAction.
func (mr *MockForManagingPlanetsMockRecorder) GetByAction(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAction", reflect.TypeOf((*MockForManagingPlanets)(nil).GetByAction), ctx, action)
}

// List mocks base method.
func (m *MockForManagingPlanets) List(ctx context.Context) ([]models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForManagingPlanetsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForManagingPlanets)(nil).List), ctx)
}

// ListForPlayer mocks base method.
func (m *MockForManagingPlanets) ListForPlayer(ctx context.Context, player uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForPlayer", ctx, player)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForPlayer indicates an expected call of ListForPlayer.
func (mr *MockForManagingPlanetsMockRecorder) ListForPlayer(ctx, player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForPlayer", reflect.TypeOf((*MockForManagingPlanets)(nil).ListForPlayer), ctx, player)
}
