// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_mutating_planet.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_mutating_planet.go -destination=drivenportstest/planet_mutator_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	drivenports "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/ports/driven"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForMutatingPlanet is a mock of ForMutatingPlanet interface.
type MockForMutatingPlanet struct {
	ctrl     *gomock.Controller
	recorder *MockForMutatingPlanetMockRecorder
	isgomock struct{}
}

// MockForMutatingPlanetMockRecorder is the mock recorder for MockForMutatingPlanet.
type MockForMutatingPlanetMockRecorder struct {
	mock *MockForMutatingPlanet
}

// NewMockForMutatingPlanet creates a new mock instance.
func NewMockForMutatingPlanet(ctrl *gomock.Controller) *MockForMutatingPlanet {
	mock := &MockForMutatingPlanet{ctrl: ctrl}
	mock.recorder = &MockForMutatingPlanetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForMutatingPlanet) EXPECT() *MockForMutatingPlanetMockRecorder {
	return m.recorder
}

// Mutate mocks base method.
func (m *MockForMutatingPlanet) Mutate(ctx context.Context, id uuid.UUID, mutator drivenports.PlanetMutator) (models.PlanetMutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mutate", ctx, id, mutator)
	ret0, _ := ret[0].(models.PlanetMutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mutate indicates an expected call of Mutate.
func (mr *MockForMutatingPlanetMockRecorder) Mutate(ctx, id, mutator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mutate", reflect.TypeOf((*MockForMutatingPlanet)(nil).Mutate), ctx, id, mutator)
}
