// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_listing_planets.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_listing_planets.go -destination=drivenportstest/planets_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForListingPlanets is a mock of ForListingPlanets interface.
type MockForListingPlanets struct {
	ctrl     *gomock.Controller
	recorder *MockForListingPlanetsMockRecorder
	isgomock struct{}
}

// MockForListingPlanetsMockRecorder is the mock recorder for MockForListingPlanets.
type MockForListingPlanetsMockRecorder struct {
	mock *MockForListingPlanets
}

// NewMockForListingPlanets creates a new mock instance.
func NewMockForListingPlanets(ctrl *gomock.Controller) *MockForListingPlanets {
	mock := &MockForListingPlanets{ctrl: ctrl}
	mock.recorder = &MockForListingPlanetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForListingPlanets) EXPECT() *MockForListingPlanetsMockRecorder {
	return m.recorder
}

// ListForPlayer mocks base method.
func (m *MockForListingPlanets) ListForPlayer(ctx context.Context, player uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForPlayer", ctx, player)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForPlayer indicates an expected call of ListForPlayer.
func (mr *MockForListingPlanetsMockRecorder) ListForPlayer(ctx, player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForPlayer", reflect.TypeOf((*MockForListingPlanets)(nil).ListForPlayer), ctx, player)
}
