// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_managing_players.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_managing_players.go -destination=drivenportstest/players_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingPlayers is a mock of ForManagingPlayers interface.
type MockForManagingPlayers struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingPlayersMockRecorder
	isgomock struct{}
}

// MockForManagingPlayersMockRecorder is the mock recorder for MockForManagingPlayers.
type MockForManagingPlayersMockRecorder struct {
	mock *MockForManagingPlayers
}

// NewMockForManagingPlayers creates a new mock instance.
func NewMockForManagingPlayers(ctrl *gomock.Controller) *MockForManagingPlayers {
	mock := &MockForManagingPlayers{ctrl: ctrl}
	mock.recorder = &MockForManagingPlayersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingPlayers) EXPECT() *MockForManagingPlayersMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForManagingPlayers) Create(ctx context.Context, player models.Player, homeworld models.Planet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, player, homeworld)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockForManagingPlayersMockRecorder) Create(ctx, player, homeworld any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForManagingPlayers)(nil).Create), ctx, player, homeworld)
}

// Delete mocks base method.
func (m *MockForManagingPlayers) Delete(ctx context.Context, player models.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, player)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingPlayersMockRecorder) Delete(ctx, player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingPlayers)(nil).Delete), ctx, player)
}

// Get mocks base method.
func (m *MockForManagingPlayers) Get(ctx context.Context, id uuid.UUID) (models.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForManagingPlayersMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForManagingPlayers)(nil).Get), ctx, id)
}

// ListForApiUser mocks base method.
func (m *MockForManagingPlayers) ListForApiUser(ctx context.Context, apiUser uuid.UUID) ([]models.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForApiUser", ctx, apiUser)
	ret0, _ := ret[0].([]models.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForApiUser indicates an expected call of ListForApiUser.
func (mr *MockForManagingPlayersMockRecorder) ListForApiUser(ctx, apiUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForApiUser", reflect.TypeOf((*MockForManagingPlayers)(nil).ListForApiUser), ctx, apiUser)
}
