// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_listing_resources.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_listing_resources.go -destination=drivenportstest/resources_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	gomock "go.uber.org/mock/gomock"
)

// MockForListingResources is a mock of ForListingResources interface.
type MockForListingResources struct {
	ctrl     *gomock.Controller
	recorder *MockForListingResourcesMockRecorder
	isgomock struct{}
}

// MockForListingResourcesMockRecorder is the mock recorder for MockForListingResources.
type MockForListingResourcesMockRecorder struct {
	mock *MockForListingResources
}

// NewMockForListingResources creates a new mock instance.
func NewMockForListingResources(ctrl *gomock.Controller) *MockForListingResources {
	mock := &MockForListingResources{ctrl: ctrl}
	mock.recorder = &MockForListingResourcesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForListingResources) EXPECT() *MockForListingResourcesMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockForListingResources) List(ctx context.Context) ([]models.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForListingResourcesMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForListingResources)(nil).List), ctx)
}
