// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_fetching_ship.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_fetching_ship.go -destination=drivenportstest/ships_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForFetchingShip is a mock of ForFetchingShip interface.
type MockForFetchingShip struct {
	ctrl     *gomock.Controller
	recorder *MockForFetchingShipMockRecorder
	isgomock struct{}
}

// MockForFetchingShipMockRecorder is the mock recorder for MockForFetchingShip.
type MockForFetchingShipMockRecorder struct {
	mock *MockForFetchingShip
}

// NewMockForFetchingShip creates a new mock instance.
func NewMockForFetchingShip(ctrl *gomock.Controller) *MockForFetchingShip {
	mock := &MockForFetchingShip{ctrl: ctrl}
	mock.recorder = &MockForFetchingShipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForFetchingShip) EXPECT() *MockForFetchingShipMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockForFetchingShip) Get(ctx context.Context, id uuid.UUID) (models.Ship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Ship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForFetchingShipMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForFetchingShip)(nil).Get), ctx, id)
}
