// Code generated by MockGen. DO NOT EDIT.
// Source: ../ports/driven/for_fetching_time.go
//
// Generated by this command:
//
//	mockgen -source=../ports/driven/for_fetching_time.go -destination=drivenportstest/time_mocks.go -package=drivenportstest
//

// Package drivenportstest is a generated GoMock package.
package drivenportstest

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockForFetchingTime is a mock of ForFetchingTime interface.
type MockForFetchingTime struct {
	ctrl     *gomock.Controller
	recorder *MockForFetchingTimeMockRecorder
	isgomock struct{}
}

// MockForFetchingTimeMockRecorder is the mock recorder for MockForFetchingTime.
type MockForFetchingTimeMockRecorder struct {
	mock *MockForFetchingTime
}

// NewMockForFetchingTime creates a new mock instance.
func NewMockForFetchingTime(ctrl *gomock.Controller) *MockForFetchingTime {
	mock := &MockForFetchingTime{ctrl: ctrl}
	mock.recorder = &MockForFetchingTimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForFetchingTime) EXPECT() *MockForFetchingTimeMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockForFetchingTime) Now(ctx context.Context) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now", ctx)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockForFetchingTimeMockRecorder) Now(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockForFetchingTime)(nil).Now), ctx)
}
