package mappers

import (
	"fmt"
	"strings"
	"time"
)

// toIso8601Duration converts a time.Duration to a string in ISO8601 format
// for a duration. This code was generated by AI.
// More information on the format can be found here:
// https://en.wikipedia.org/wiki/ISO_8601#Durations
func toIso8601Duration(duration time.Duration) string {
	if duration == 0 {
		return "PT0S"
	}

	sign := ""
	if duration < 0 {
		sign = "-"
		duration = duration.Abs()
	}

	const day = 24 * time.Hour

	days := duration / day
	duration %= day

	hours := duration / time.Hour
	duration %= time.Hour

	minutes := duration / time.Minute
	duration %= time.Minute

	seconds := duration / time.Second
	nanoseconds := duration % time.Second

	var result strings.Builder
	result.WriteString(sign)
	result.WriteString("P")

	if days > 0 {
		fmt.Fprintf(&result, "%dD", days)
	}

	if hours > 0 || minutes > 0 || seconds > 0 || nanoseconds > 0 {
		result.WriteString("T")

		if hours > 0 {
			fmt.Fprintf(&result, "%dH", hours)
		}

		if minutes > 0 {
			fmt.Fprintf(&result, "%dM", minutes)
		}

		if nanoseconds > 0 {
			fraction := fmt.Sprintf("%09d", nanoseconds)
			fraction = strings.TrimRight(fraction, "0")
			fmt.Fprintf(&result, "%d.%sS", seconds, fraction)
		} else if seconds > 0 {
			fmt.Fprintf(&result, "%dS", seconds)
		}
	}

	return result.String()
}
