# https://doc.traefik.io/traefik/routing/services/#configuration-examples
http:
  routers:
    auth-service-https:
      entryPoints:
        - "websecure"
      rule: 'Host(`auth.{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/v1`)'
      service: auth-service
      tls:
        certResolver: letsencryptresolver

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:80"
        healthCheck:
          path: /v1/healthcheck
