http:
  routers:
    galactic-sovereign-service-https:
      entryPoints:
        - "websecure"
      rule: 'Host(`api.{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/v1/galactic-sovereign`)'
      service: galactic-sovereign-service
      middlewares:
        - "rate-limit"
        - "auth"
      tls:
        certResolver: letsencryptresolver

  middlewares:
    rate-limit:
      rateLimit:
        average: 5
        burst: 10
    auth:
      # https://doc.traefik.io/traefik/middlewares/http/forwardauth
      forwardAuth:
        address: "http://user-service:80/v1/users/auth"
        authResponseHeaders:
          - "X-Acl"
          - "X-User-Limit"

  services:
    galactic-sovereign-service:
      loadBalancer:
        servers:
          - url: "http://galactic-sovereign-service:80"
        healthCheck:
          path: /v1/galactic-sovereign/healthcheck
