http:
  routers:
    stellar-dominion-https:
      entryPoints:
        - "websecure"
      rule: 'Host(`{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/`)'
      service: stellar-dominion
      tls:
        certResolver: letsencryptresolver

    stellar-dominion-www-https:
      entryPoints:
        - "websecure"
      rule: 'Host(`www.{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/`)'
      middlewares:
        - "ws-redirect"
      service: stellar-dominion
      tls:
        certResolver: letsencryptresolver

  middlewares:
    ws-redirect:
      redirectRegex:
        regex: '^https://www.{{ env "DOMAIN_NAME" }}/(.*)'
        replacement: 'https://{{ env "DOMAIN_NAME" }}/${1}'

  services:
    stellar-dominion:
      loadBalancer:
        servers:
          - url: "http://stellar-dominion:3001"
