http:
  routers:
    stellar-dominion-service-https:
      entryPoints:
        - "websecure"
      rule: 'Host(`api.{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/v1`)'
      service: stellar-dominion-service
      middlewares:
        - "sd-rate-limit"
        - "sd-auth"
      tls:
        certResolver: letsencryptresolver

  middlewares:
    sd-rate-limit:
      rateLimit:
        average: 5
        burst: 10
    sd-auth:
      forwardAuth:
        address: "http://user-service:80/v1/users/auth"
        authResponseHeaders:
          - "X-Acl"
          - "X-User-Limit"

  services:
    stellar-dominion-service:
      loadBalancer:
        servers:
          - url: "http://stellar-dominion-service:80"
        healthCheck:
          path: /v1/healthcheck
