http:
  routers:
    # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
    traefik-dashboard:
      rule: 'Host(`{{ env "DEPLOY_HOST" }}`) && PathPrefix(`/traefik`)'
      entryPoints: web
      service: api@internal
