http:
  routers:
    # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
    traefik-dashboard-https:
      rule: 'Host(`traefik.{{ env "DOMAIN_NAME" }}`)'
      entryPoints:
        - "websecure"
      service: api@internal
      middlewares:
        - "td-auth"
      tls:
        certResolver: letsencryptresolver

  middlewares:
    td-auth:
      # https://doc.traefik.io/traefik/middlewares/http/basicauth/#configuration-examples
      basicAuth:
        users: '{{ env "TRAEFIK_USER"}}:{{ env "TRAEFIK_HASHED_PASSWORD" }}'
