http:
  routers:
    # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
    traefik-dashboard:
      rule: 'Host(`{{ env "TRAEFIK_DEPLOY_HOST" }}`)'
      entryPoints: web
      service: api@internal
      priority: 3
