http:
  routers:
    # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
    traefik-dashboard:
      rule: "PathPrefix(`/traefik`) || (PathPrefix(`/api`) && !PathPrefix(`/api/v1`))"
      entryPoints: web
      service: api@internal
      middlewares:
        - "td-strip-path-prefix"
        - "td-auth"

  middlewares:
    td-strip-path-prefix:
      stripPrefix:
        prefixes:
          - "/traefik"
    td-auth:
      basicAuth:
        users: '{{ env "TRAEFIK_USER"}}:{{ env "TRAEFIK_HASHED_PASSWORD" }}'
