# https://doc.traefik.io/traefik/routing/services/#configuration-examples
http:
  routers:
    user-service:
      entryPoints:
        - "web"
      rule: "PathPrefix(`/api/v1`)"
      service: user-service
      middlewares:
        - "user-service-strip-prefix"

  middlewares:
    user-service-strip-prefix:
      stripPrefix:
        prefixes:
          - "/api"

  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:80"
