# https://doc.traefik.io/traefik/routing/services/#configuration-examples
http:
  routers:
    user-service:
      entryPoints:
        - "web"
      rule: 'HostRegexp(`api.{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/v1`)'
      service: user-service
      middlewares:
        - "us-rate-limit"

  middlewares:
    us-rate-limit:
      rateLimit:
        average: 5
        burst: 10

  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:80"
