# https://doc.traefik.io/traefik/routing/services/#configuration-examples
http:
  routers:
    user-service:
      entryPoints:
        - "web"
      rule: "PathPrefix(`/api/v1`)"
      service: user-service
      middlewares:
        - "strip-path-prefix"
        - "rate-limit"

  middlewares:
    strip-path-prefix:
      stripPrefix:
        prefixes:
          - "/api"
    rate-limit:
      rateLimit:
        average: 5
        burst: 10

  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:80"
