# https://doc.traefik.io/traefik/routing/services/#configuration-examples
http:
  middlewares:
    us-rate-limit:
      rateLimit:
        average: 5
        burst: 10

  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:80"
        healthCheck:
          path: /v1/healthcheck
