# https://doc.traefik.io/traefik/routing/services/#configuration-examples
http:
  routers:
    webserver:
      entryPoints:
        - "web"
      rule: 'Host(`{{ env "WEBSERVER_DEPLOY_HOST" }}`)'
      service: webserver
      # https://doc.traefik.io/traefik/routing/routers/#priority
      priority: 1

  services:
    webserver:
      loadBalancer:
        servers:
          - url: "http://webserver:3001"
