# https://doc.traefik.io/traefik/routing/services/#configuration-examples
http:
  routers:
    webserver:
      entryPoints:
        - "web"
      rule: 'Host(`{{ env "DEPLOY_HOST" }}`) && PathPrefix(`/dashboard`)'
      service: webserver

  services:
    webserver:
      loadBalancer:
        servers:
          - url: "http://webserver:3001"
