// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_managing_building_action.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_managing_building_action.go -destination=drivingportstest/building_action_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingBuildingAction is a mock of ForManagingBuildingAction interface.
type MockForManagingBuildingAction struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingBuildingActionMockRecorder
	isgomock struct{}
}

// MockForManagingBuildingActionMockRecorder is the mock recorder for MockForManagingBuildingAction.
type MockForManagingBuildingActionMockRecorder struct {
	mock *MockForManagingBuildingAction
}

// NewMockForManagingBuildingAction creates a new mock instance.
func NewMockForManagingBuildingAction(ctrl *gomock.Controller) *MockForManagingBuildingAction {
	mock := &MockForManagingBuildingAction{ctrl: ctrl}
	mock.recorder = &MockForManagingBuildingActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingBuildingAction) EXPECT() *MockForManagingBuildingActionMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockForManagingBuildingAction) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingBuildingActionMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingBuildingAction)(nil).Delete), ctx, id)
}
