// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_creating_fleet.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_creating_fleet.go -destination=drivingportstest/create_fleet_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	gomock "go.uber.org/mock/gomock"
)

// MockForCreatingFleet is a mock of ForCreatingFleet interface.
type MockForCreatingFleet struct {
	ctrl     *gomock.Controller
	recorder *MockForCreatingFleetMockRecorder
	isgomock struct{}
}

// MockForCreatingFleetMockRecorder is the mock recorder for MockForCreatingFleet.
type MockForCreatingFleetMockRecorder struct {
	mock *MockForCreatingFleet
}

// NewMockForCreatingFleet creates a new mock instance.
func NewMockForCreatingFleet(ctrl *gomock.Controller) *MockForCreatingFleet {
	mock := &MockForCreatingFleet{ctrl: ctrl}
	mock.recorder = &MockForCreatingFleetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCreatingFleet) EXPECT() *MockForCreatingFleetMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForCreatingFleet) Create(ctx context.Context, req request.FleetCreationRequest) (models.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(models.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockForCreatingFleetMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForCreatingFleet)(nil).Create), ctx, req)
}
