// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_creating_ship.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_creating_ship.go -destination=drivingportstest/create_ship_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	gomock "go.uber.org/mock/gomock"
)

// MockForCreatingShip is a mock of ForCreatingShip interface.
type MockForCreatingShip struct {
	ctrl     *gomock.Controller
	recorder *MockForCreatingShipMockRecorder
	isgomock struct{}
}

// MockForCreatingShipMockRecorder is the mock recorder for MockForCreatingShip.
type MockForCreatingShipMockRecorder struct {
	mock *MockForCreatingShip
}

// NewMockForCreatingShip creates a new mock instance.
func NewMockForCreatingShip(ctrl *gomock.Controller) *MockForCreatingShip {
	mock := &MockForCreatingShip{ctrl: ctrl}
	mock.recorder = &MockForCreatingShipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCreatingShip) EXPECT() *MockForCreatingShipMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForCreatingShip) Create(ctx context.Context, req request.ShipCreationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockForCreatingShipMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForCreatingShip)(nil).Create), ctx, req)
}
