// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_creating_planet.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_creating_planet.go -destination=drivingportstest/create_planet_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	gomock "go.uber.org/mock/gomock"
)

// MockForCreatingPlanet is a mock of ForCreatingPlanet interface.
type MockForCreatingPlanet struct {
	ctrl     *gomock.Controller
	recorder *MockForCreatingPlanetMockRecorder
	isgomock struct{}
}

// MockForCreatingPlanetMockRecorder is the mock recorder for MockForCreatingPlanet.
type MockForCreatingPlanetMockRecorder struct {
	mock *MockForCreatingPlanet
}

// NewMockForCreatingPlanet creates a new mock instance.
func NewMockForCreatingPlanet(ctrl *gomock.Controller) *MockForCreatingPlanet {
	mock := &MockForCreatingPlanet{ctrl: ctrl}
	mock.recorder = &MockForCreatingPlanetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCreatingPlanet) EXPECT() *MockForCreatingPlanetMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForCreatingPlanet) Create(ctx context.Context, req request.PlanetCreationRequest) (models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockForCreatingPlanetMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForCreatingPlanet)(nil).Create), ctx, req)
}
