// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_creating_building_action.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_creating_building_action.go -destination=drivingportstest/create_building_action_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	gomock "go.uber.org/mock/gomock"
)

// MockForCreatingBuildingAction is a mock of ForCreatingBuildingAction interface.
type MockForCreatingBuildingAction struct {
	ctrl     *gomock.Controller
	recorder *MockForCreatingBuildingActionMockRecorder
	isgomock struct{}
}

// MockForCreatingBuildingActionMockRecorder is the mock recorder for MockForCreatingBuildingAction.
type MockForCreatingBuildingActionMockRecorder struct {
	mock *MockForCreatingBuildingAction
}

// NewMockForCreatingBuildingAction creates a new mock instance.
func NewMockForCreatingBuildingAction(ctrl *gomock.Controller) *MockForCreatingBuildingAction {
	mock := &MockForCreatingBuildingAction{ctrl: ctrl}
	mock.recorder = &MockForCreatingBuildingActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCreatingBuildingAction) EXPECT() *MockForCreatingBuildingActionMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForCreatingBuildingAction) Create(ctx context.Context, req request.BuildingActionCreationRequest) (models.BuildingAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(models.BuildingAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockForCreatingBuildingActionMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForCreatingBuildingAction)(nil).Create), ctx, req)
}
