// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_creating_ship_action.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_creating_ship_action.go -destination=drivingportstest/create_ship_action_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	gomock "go.uber.org/mock/gomock"
)

// MockForCreatingShipAction is a mock of ForCreatingShipAction interface.
type MockForCreatingShipAction struct {
	ctrl     *gomock.Controller
	recorder *MockForCreatingShipActionMockRecorder
	isgomock struct{}
}

// MockForCreatingShipActionMockRecorder is the mock recorder for MockForCreatingShipAction.
type MockForCreatingShipActionMockRecorder struct {
	mock *MockForCreatingShipAction
}

// NewMockForCreatingShipAction creates a new mock instance.
func NewMockForCreatingShipAction(ctrl *gomock.Controller) *MockForCreatingShipAction {
	mock := &MockForCreatingShipAction{ctrl: ctrl}
	mock.recorder = &MockForCreatingShipActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCreatingShipAction) EXPECT() *MockForCreatingShipActionMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForCreatingShipAction) Create(ctx context.Context, req request.ShipActionCreationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockForCreatingShipActionMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForCreatingShipAction)(nil).Create), ctx, req)
}
