// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_deleting_building_action.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_deleting_building_action.go -destination=drivingportstest/deleting_building_action_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForDeletingBuildingAction is a mock of ForDeletingBuildingAction interface.
type MockForDeletingBuildingAction struct {
	ctrl     *gomock.Controller
	recorder *MockForDeletingBuildingActionMockRecorder
	isgomock struct{}
}

// MockForDeletingBuildingActionMockRecorder is the mock recorder for MockForDeletingBuildingAction.
type MockForDeletingBuildingActionMockRecorder struct {
	mock *MockForDeletingBuildingAction
}

// NewMockForDeletingBuildingAction creates a new mock instance.
func NewMockForDeletingBuildingAction(ctrl *gomock.Controller) *MockForDeletingBuildingAction {
	mock := &MockForDeletingBuildingAction{ctrl: ctrl}
	mock.recorder = &MockForDeletingBuildingActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForDeletingBuildingAction) EXPECT() *MockForDeletingBuildingActionMockRecorder {
	return m.recorder
}

// DeleteForPlanet mocks base method.
func (m *MockForDeletingBuildingAction) DeleteForPlanet(ctx context.Context, planet uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForPlanet", ctx, planet)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForPlanet indicates an expected call of DeleteForPlanet.
func (mr *MockForDeletingBuildingActionMockRecorder) DeleteForPlanet(ctx, planet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForPlanet", reflect.TypeOf((*MockForDeletingBuildingAction)(nil).DeleteForPlanet), ctx, planet)
}
