// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_deleting_planet.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_deleting_planet.go -destination=drivingportstest/delete_planet_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForDeletingPlanet is a mock of ForDeletingPlanet interface.
type MockForDeletingPlanet struct {
	ctrl     *gomock.Controller
	recorder *MockForDeletingPlanetMockRecorder
	isgomock struct{}
}

// MockForDeletingPlanetMockRecorder is the mock recorder for MockForDeletingPlanet.
type MockForDeletingPlanetMockRecorder struct {
	mock *MockForDeletingPlanet
}

// NewMockForDeletingPlanet creates a new mock instance.
func NewMockForDeletingPlanet(ctrl *gomock.Controller) *MockForDeletingPlanet {
	mock := &MockForDeletingPlanet{ctrl: ctrl}
	mock.recorder = &MockForDeletingPlanetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForDeletingPlanet) EXPECT() *MockForDeletingPlanetMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockForDeletingPlanet) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForDeletingPlanetMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForDeletingPlanet)(nil).Delete), ctx, id)
}
