// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_fetching_planets.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_fetching_planets.go -destination=drivingportstest/fetch_planets_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForFetchingPlanets is a mock of ForFetchingPlanets interface.
type MockForFetchingPlanets struct {
	ctrl     *gomock.Controller
	recorder *MockForFetchingPlanetsMockRecorder
	isgomock struct{}
}

// MockForFetchingPlanetsMockRecorder is the mock recorder for MockForFetchingPlanets.
type MockForFetchingPlanetsMockRecorder struct {
	mock *MockForFetchingPlanets
}

// NewMockForFetchingPlanets creates a new mock instance.
func NewMockForFetchingPlanets(ctrl *gomock.Controller) *MockForFetchingPlanets {
	mock := &MockForFetchingPlanets{ctrl: ctrl}
	mock.recorder = &MockForFetchingPlanetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForFetchingPlanets) EXPECT() *MockForFetchingPlanetsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockForFetchingPlanets) Get(ctx context.Context, id uuid.UUID) (models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForFetchingPlanetsMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForFetchingPlanets)(nil).Get), ctx, id)
}

// ListForPlayer mocks base method.
func (m *MockForFetchingPlanets) ListForPlayer(ctx context.Context, player uuid.UUID) ([]models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForPlayer", ctx, player)
	ret0, _ := ret[0].([]models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForPlayer indicates an expected call of ListForPlayer.
func (mr *MockForFetchingPlanetsMockRecorder) ListForPlayer(ctx, player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForPlayer", reflect.TypeOf((*MockForFetchingPlanets)(nil).ListForPlayer), ctx, player)
}
