// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_fetching_solar_system.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_fetching_solar_system.go -destination=drivingportstest/fetching_solar_system_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForFetchingSolarSystem is a mock of ForFetchingSolarSystem interface.
type MockForFetchingSolarSystem struct {
	ctrl     *gomock.Controller
	recorder *MockForFetchingSolarSystemMockRecorder
	isgomock struct{}
}

// MockForFetchingSolarSystemMockRecorder is the mock recorder for MockForFetchingSolarSystem.
type MockForFetchingSolarSystemMockRecorder struct {
	mock *MockForFetchingSolarSystem
}

// NewMockForFetchingSolarSystem creates a new mock instance.
func NewMockForFetchingSolarSystem(ctrl *gomock.Controller) *MockForFetchingSolarSystem {
	mock := &MockForFetchingSolarSystem{ctrl: ctrl}
	mock.recorder = &MockForFetchingSolarSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForFetchingSolarSystem) EXPECT() *MockForFetchingSolarSystemMockRecorder {
	return m.recorder
}

// GetSolarSystem mocks base method.
func (m *MockForFetchingSolarSystem) GetSolarSystem(ctx context.Context, universe uuid.UUID, galaxy, solarSystem int) (models.SolarSystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSolarSystem", ctx, universe, galaxy, solarSystem)
	ret0, _ := ret[0].(models.SolarSystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSolarSystem indicates an expected call of GetSolarSystem.
func (mr *MockForFetchingSolarSystemMockRecorder) GetSolarSystem(ctx, universe, galaxy, solarSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSolarSystem", reflect.TypeOf((*MockForFetchingSolarSystem)(nil).GetSolarSystem), ctx, universe, galaxy, solarSystem)
}
