// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_checking_service_health.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_checking_service_health.go -destination=drivingportstest/health_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockForCheckingServiceHealth is a mock of ForCheckingServiceHealth interface.
type MockForCheckingServiceHealth struct {
	ctrl     *gomock.Controller
	recorder *MockForCheckingServiceHealthMockRecorder
	isgomock struct{}
}

// MockForCheckingServiceHealthMockRecorder is the mock recorder for MockForCheckingServiceHealth.
type MockForCheckingServiceHealthMockRecorder struct {
	mock *MockForCheckingServiceHealth
}

// NewMockForCheckingServiceHealth creates a new mock instance.
func NewMockForCheckingServiceHealth(ctrl *gomock.Controller) *MockForCheckingServiceHealth {
	mock := &MockForCheckingServiceHealth{ctrl: ctrl}
	mock.recorder = &MockForCheckingServiceHealthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCheckingServiceHealth) EXPECT() *MockForCheckingServiceHealthMockRecorder {
	return m.recorder
}

// Healthy mocks base method.
func (m *MockForCheckingServiceHealth) Healthy(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockForCheckingServiceHealthMockRecorder) Healthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockForCheckingServiceHealth)(nil).Healthy), ctx)
}
