// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_managing_universe.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_managing_universe.go -destination=drivingportstest/mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingUniverse is a mock of ForManagingUniverse interface.
type MockForManagingUniverse struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingUniverseMockRecorder
	isgomock struct{}
}

// MockForManagingUniverseMockRecorder is the mock recorder for MockForManagingUniverse.
type MockForManagingUniverseMockRecorder struct {
	mock *MockForManagingUniverse
}

// NewMockForManagingUniverse creates a new mock instance.
func NewMockForManagingUniverse(ctrl *gomock.Controller) *MockForManagingUniverse {
	mock := &MockForManagingUniverse{ctrl: ctrl}
	mock.recorder = &MockForManagingUniverseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingUniverse) EXPECT() *MockForManagingUniverseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForManagingUniverse) Create(ctx context.Context, req request.UniverseCreationRequest) (models.Universe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(models.Universe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockForManagingUniverseMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForManagingUniverse)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockForManagingUniverse) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingUniverseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingUniverse)(nil).Delete), ctx, id)
}
