// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_creating_universe.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_creating_universe.go -destination=drivingportstest/mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	gomock "go.uber.org/mock/gomock"
)

// MockForCreatingUniverse is a mock of ForCreatingUniverse interface.
type MockForCreatingUniverse struct {
	ctrl     *gomock.Controller
	recorder *MockForCreatingUniverseMockRecorder
	isgomock struct{}
}

// MockForCreatingUniverseMockRecorder is the mock recorder for MockForCreatingUniverse.
type MockForCreatingUniverseMockRecorder struct {
	mock *MockForCreatingUniverse
}

// NewMockForCreatingUniverse creates a new mock instance.
func NewMockForCreatingUniverse(ctrl *gomock.Controller) *MockForCreatingUniverse {
	mock := &MockForCreatingUniverse{ctrl: ctrl}
	mock.recorder = &MockForCreatingUniverseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForCreatingUniverse) EXPECT() *MockForCreatingUniverseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForCreatingUniverse) Create(ctx context.Context, req request.UniverseCreationRequest) (models.Universe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(models.Universe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockForCreatingUniverseMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForCreatingUniverse)(nil).Create), ctx, req)
}
