// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_managing_planet.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_managing_planet.go -destination=drivingportstest/planet_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingPlanet is a mock of ForManagingPlanet interface.
type MockForManagingPlanet struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingPlanetMockRecorder
	isgomock struct{}
}

// MockForManagingPlanetMockRecorder is the mock recorder for MockForManagingPlanet.
type MockForManagingPlanetMockRecorder struct {
	mock *MockForManagingPlanet
}

// NewMockForManagingPlanet creates a new mock instance.
func NewMockForManagingPlanet(ctrl *gomock.Controller) *MockForManagingPlanet {
	mock := &MockForManagingPlanet{ctrl: ctrl}
	mock.recorder = &MockForManagingPlanetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingPlanet) EXPECT() *MockForManagingPlanetMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForManagingPlanet) Create(ctx context.Context, req request.PlanetCreationRequest) (models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockForManagingPlanetMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForManagingPlanet)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockForManagingPlanet) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingPlanetMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingPlanet)(nil).Delete), ctx, id)
}

// DeleteForPlayer mocks base method.
func (m *MockForManagingPlanet) DeleteForPlayer(ctx context.Context, player uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForPlayer", ctx, player)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForPlayer indicates an expected call of DeleteForPlayer.
func (mr *MockForManagingPlanetMockRecorder) DeleteForPlayer(ctx, player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForPlayer", reflect.TypeOf((*MockForManagingPlanet)(nil).DeleteForPlayer), ctx, player)
}

// Get mocks base method.
func (m *MockForManagingPlanet) Get(ctx context.Context, id uuid.UUID) (models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForManagingPlanetMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForManagingPlanet)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockForManagingPlanet) List(ctx context.Context) ([]models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForManagingPlanetMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForManagingPlanet)(nil).List), ctx)
}

// ListForPlayer mocks base method.
func (m *MockForManagingPlanet) ListForPlayer(ctx context.Context, player uuid.UUID) ([]models.Planet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForPlayer", ctx, player)
	ret0, _ := ret[0].([]models.Planet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForPlayer indicates an expected call of ListForPlayer.
func (mr *MockForManagingPlanetMockRecorder) ListForPlayer(ctx, player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForPlayer", reflect.TypeOf((*MockForManagingPlanet)(nil).ListForPlayer), ctx, player)
}
