// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/ports/driving/for_managing_player.go
//
// Generated by this command:
//
//	mockgen -source=../../app/ports/driving/for_managing_player.go -destination=drivingportstest/player_mocks.go -package=drivingportstest
//

// Package drivingportstest is a generated GoMock package.
package drivingportstest

import (
	context "context"
	reflect "reflect"

	models "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models"
	request "github.com/Knoblauchpilze/galactic-sovereign/pkg/domain/app/models/request"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForManagingPlayer is a mock of ForManagingPlayer interface.
type MockForManagingPlayer struct {
	ctrl     *gomock.Controller
	recorder *MockForManagingPlayerMockRecorder
	isgomock struct{}
}

// MockForManagingPlayerMockRecorder is the mock recorder for MockForManagingPlayer.
type MockForManagingPlayerMockRecorder struct {
	mock *MockForManagingPlayer
}

// NewMockForManagingPlayer creates a new mock instance.
func NewMockForManagingPlayer(ctrl *gomock.Controller) *MockForManagingPlayer {
	mock := &MockForManagingPlayer{ctrl: ctrl}
	mock.recorder = &MockForManagingPlayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForManagingPlayer) EXPECT() *MockForManagingPlayerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockForManagingPlayer) Create(ctx context.Context, req request.PlayerCreationRequest) (models.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(models.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockForManagingPlayerMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockForManagingPlayer)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockForManagingPlayer) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockForManagingPlayerMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockForManagingPlayer)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockForManagingPlayer) Get(ctx context.Context, id uuid.UUID) (models.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockForManagingPlayerMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockForManagingPlayer)(nil).Get), ctx, id)
}

// ListForApiUser mocks base method.
func (m *MockForManagingPlayer) ListForApiUser(ctx context.Context, apiUser uuid.UUID) ([]models.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForApiUser", ctx, apiUser)
	ret0, _ := ret[0].([]models.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForApiUser indicates an expected call of ListForApiUser.
func (mr *MockForManagingPlayerMockRecorder) ListForApiUser(ctx, apiUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForApiUser", reflect.TypeOf((*MockForManagingPlayer)(nil).ListForApiUser), ctx, apiUser)
}
