// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actions/{id}": {
            "delete": {
                "description": "Deletes an existing building action.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Delete building action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Action id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No such action",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Returns service health based on database connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/planets": {
            "get": {
                "description": "Returns planets, optionally filtered by player id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "List planets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player id (UUID)",
                        "name": "player",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.PlanetResponseDoc"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a planet from the provided payload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "Create planet",
                "parameters": [
                    {
                        "description": "Planet payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.PlanetRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.PlanetResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid planet syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/planets/{id}": {
            "get": {
                "description": "Returns a planet and all related game data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "Get planet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Planet id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.FullPlanetResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No such planet",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a planet by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "Delete planet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Planet id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No such planet",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/planets/{id}/actions": {
            "post": {
                "description": "Creates a building action for the planet provided in path parameter. The planet field in the body is ignored and replaced with this path value.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Create building action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Planet id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Building action payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.BuildingActionRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.BuildingActionResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax, invalid payload syntax or not enough resources",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Building action already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/players": {
            "get": {
                "description": "Returns players, optionally filtered by api_user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "List players",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API user id (UUID)",
                        "name": "api_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.PlayerResponseDoc"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a player and its homeworld.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Create player",
                "parameters": [
                    {
                        "description": "Player payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.PlayerRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.PlayerResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid player syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Name already used",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/players/{id}": {
            "get": {
                "description": "Returns a player by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Get player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.PlayerResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No such player",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a player by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Delete player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No such player",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/universes": {
            "get": {
                "description": "Returns all universes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universes"
                ],
                "summary": "List universes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.UniverseResponseDoc"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a universe.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universes"
                ],
                "summary": "Create universe",
                "parameters": [
                    {
                        "description": "Universe payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UniverseRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.UniverseResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid universe syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Name already used",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        },
        "/universes/{id}": {
            "get": {
                "description": "Returns a universe and related resources/buildings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universes"
                ],
                "summary": "Get universe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Universe id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.FullUniverseResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No such universe",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a universe by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universes"
                ],
                "summary": "Delete universe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Universe id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No such universe",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ToolkitErrorDoc"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.BuildingActionRequestDoc": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "planet": {
                    "type": "string"
                }
            }
        },
        "controller.BuildingActionResponseDoc": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentLevel": {
                    "type": "integer"
                },
                "desiredLevel": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "planet": {
                    "type": "string"
                }
            }
        },
        "controller.BuildingCostResponseDoc": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                },
                "progress": {
                    "type": "number"
                },
                "resource": {
                    "type": "string"
                }
            }
        },
        "controller.BuildingResourceProductionResponseDoc": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "integer"
                },
                "building": {
                    "type": "string"
                },
                "progress": {
                    "type": "number"
                },
                "resource": {
                    "type": "string"
                }
            }
        },
        "controller.BuildingResourceStorageResponseDoc": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "integer"
                },
                "building": {
                    "type": "string"
                },
                "progress": {
                    "type": "number"
                },
                "resource": {
                    "type": "string"
                },
                "scale": {
                    "type": "number"
                }
            }
        },
        "controller.FullBuildingResponseDoc": {
            "type": "object",
            "properties": {
                "costs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.BuildingCostResponseDoc"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "productions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.BuildingResourceProductionResponseDoc"
                    }
                },
                "storages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.BuildingResourceStorageResponseDoc"
                    }
                }
            }
        },
        "controller.FullPlanetResponseDoc": {
            "type": "object",
            "properties": {
                "buildingActions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.BuildingActionResponseDoc"
                    }
                },
                "buildings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.PlanetBuildingResponseDoc"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "homeworld": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "player": {
                    "type": "string"
                },
                "productions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.PlanetResourceProductionResponseDoc"
                    }
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.PlanetResourceResponseDoc"
                    }
                },
                "storages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.PlanetResourceStorageResponseDoc"
                    }
                }
            }
        },
        "controller.FullUniverseResponseDoc": {
            "type": "object",
            "properties": {
                "buildings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.FullBuildingResponseDoc"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.ResourceResponseDoc"
                    }
                }
            }
        },
        "controller.PlanetBuildingResponseDoc": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "planet": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "controller.PlanetRequestDoc": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "player": {
                    "type": "string"
                }
            }
        },
        "controller.PlanetResourceProductionResponseDoc": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "planet": {
                    "type": "string"
                },
                "production": {
                    "type": "integer"
                },
                "resource": {
                    "type": "string"
                }
            }
        },
        "controller.PlanetResourceResponseDoc": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "planet": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "controller.PlanetResourceStorageResponseDoc": {
            "type": "object",
            "properties": {
                "planet": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "storage": {
                    "type": "integer"
                }
            }
        },
        "controller.PlanetResponseDoc": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "homeworld": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "player": {
                    "type": "string"
                }
            }
        },
        "controller.PlayerRequestDoc": {
            "type": "object",
            "properties": {
                "api_user": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "universe": {
                    "type": "string"
                }
            }
        },
        "controller.PlayerResponseDoc": {
            "type": "object",
            "properties": {
                "api_user": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "universe": {
                    "type": "string"
                }
            }
        },
        "controller.ResourceResponseDoc": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.ToolkitErrorDoc": {
            "type": "object",
            "properties": {
                "Cause": {},
                "Message": {
                    "type": "string"
                },
                "Value": {
                    "type": "integer"
                }
            }
        },
        "controller.UniverseRequestDoc": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.UniverseResponseDoc": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1/galactic-sovereign",
	Schemes:          []string{},
	Title:            "Galactic Sovereign API",
	Description:      "REST API for the Galactic Sovereign backend service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
