// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "communication.BuildingActionDtoRequest": {
                "properties": {
                    "building": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "planet": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.BuildingActionDtoResponse": {
                "properties": {
                    "building": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "completedAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "currentLevel": {
                        "type": "integer"
                    },
                    "desiredLevel": {
                        "type": "integer"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "planet": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.BuildingCostDtoResponse": {
                "properties": {
                    "building": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "cost": {
                        "type": "integer"
                    },
                    "progress": {
                        "type": "number"
                    },
                    "resource": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.BuildingResourceProductionDtoResponse": {
                "properties": {
                    "base": {
                        "type": "integer"
                    },
                    "building": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "progress": {
                        "type": "number"
                    },
                    "resource": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.BuildingResourceStorageDtoResponse": {
                "properties": {
                    "base": {
                        "type": "integer"
                    },
                    "building": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "progress": {
                        "type": "number"
                    },
                    "resource": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "scale": {
                        "type": "number"
                    }
                },
                "type": "object"
            },
            "communication.FullBuildingDtoResponse": {
                "properties": {
                    "costs": {
                        "items": {
                            "$ref": "#/components/schemas/communication.BuildingCostDtoResponse"
                        },
                        "type": "array"
                    },
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "productions": {
                        "items": {
                            "$ref": "#/components/schemas/communication.BuildingResourceProductionDtoResponse"
                        },
                        "type": "array"
                    },
                    "storages": {
                        "items": {
                            "$ref": "#/components/schemas/communication.BuildingResourceStorageDtoResponse"
                        },
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "communication.FullPlanetDtoResponse": {
                "properties": {
                    "buildingActions": {
                        "items": {
                            "$ref": "#/components/schemas/communication.BuildingActionDtoResponse"
                        },
                        "type": "array"
                    },
                    "buildings": {
                        "items": {
                            "$ref": "#/components/schemas/communication.PlanetBuildingDtoResponse"
                        },
                        "type": "array"
                    },
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "homeworld": {
                        "type": "boolean"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "player": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "productions": {
                        "items": {
                            "$ref": "#/components/schemas/communication.PlanetResourceProductionDtoResponse"
                        },
                        "type": "array"
                    },
                    "resources": {
                        "items": {
                            "$ref": "#/components/schemas/communication.PlanetResourceDtoResponse"
                        },
                        "type": "array"
                    },
                    "storages": {
                        "items": {
                            "$ref": "#/components/schemas/communication.PlanetResourceStorageDtoResponse"
                        },
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "communication.FullUniverseDtoResponse": {
                "properties": {
                    "buildings": {
                        "items": {
                            "$ref": "#/components/schemas/communication.FullBuildingDtoResponse"
                        },
                        "type": "array"
                    },
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "resources": {
                        "items": {
                            "$ref": "#/components/schemas/communication.ResourceDtoResponse"
                        },
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "communication.PlanetBuildingDtoResponse": {
                "properties": {
                    "building": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "level": {
                        "type": "integer"
                    },
                    "planet": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "updatedAt": {
                        "format": "date-time",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.PlanetDtoRequest": {
                "properties": {
                    "name": {
                        "form": "name",
                        "type": "string"
                    },
                    "player": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.PlanetDtoResponse": {
                "properties": {
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "homeworld": {
                        "type": "boolean"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "player": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.PlanetResourceDtoResponse": {
                "properties": {
                    "amount": {
                        "type": "number"
                    },
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "planet": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "resource": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "updatedAt": {
                        "format": "date-time",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.PlanetResourceProductionDtoResponse": {
                "properties": {
                    "building": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "planet": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "production": {
                        "type": "integer"
                    },
                    "resource": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.PlanetResourceStorageDtoResponse": {
                "properties": {
                    "planet": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "resource": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "storage": {
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "communication.PlayerDtoRequest": {
                "properties": {
                    "api_user": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "form": "name",
                        "type": "string"
                    },
                    "universe": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.PlayerDtoResponse": {
                "properties": {
                    "api_user": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "universe": {
                        "format": "uuid",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.ResourceDtoResponse": {
                "properties": {
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.UniverseDtoRequest": {
                "properties": {
                    "name": {
                        "form": "name",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "communication.UniverseDtoResponse": {
                "properties": {
                    "createdAt": {
                        "format": "date-time",
                        "type": "string"
                    },
                    "id": {
                        "format": "uuid",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-array_communication_PlanetDtoResponse": {
                "properties": {
                    "details": {
                        "items": {
                            "$ref": "#/components/schemas/communication.PlanetDtoResponse"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-array_communication_PlayerDtoResponse": {
                "properties": {
                    "details": {
                        "items": {
                            "$ref": "#/components/schemas/communication.PlayerDtoResponse"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-array_communication_UniverseDtoResponse": {
                "properties": {
                    "details": {
                        "items": {
                            "$ref": "#/components/schemas/communication.UniverseDtoResponse"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-communication_BuildingActionDtoResponse": {
                "properties": {
                    "details": {
                        "$ref": "#/components/schemas/communication.BuildingActionDtoResponse"
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-communication_FullPlanetDtoResponse": {
                "properties": {
                    "details": {
                        "$ref": "#/components/schemas/communication.FullPlanetDtoResponse"
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-communication_FullUniverseDtoResponse": {
                "properties": {
                    "details": {
                        "$ref": "#/components/schemas/communication.FullUniverseDtoResponse"
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-communication_PlanetDtoResponse": {
                "properties": {
                    "details": {
                        "$ref": "#/components/schemas/communication.PlanetDtoResponse"
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-communication_PlayerDtoResponse": {
                "properties": {
                    "details": {
                        "$ref": "#/components/schemas/communication.PlayerDtoResponse"
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-communication_UniverseDtoResponse": {
                "properties": {
                    "details": {
                        "$ref": "#/components/schemas/communication.UniverseDtoResponse"
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.ResponseEnvelope-string": {
                "properties": {
                    "details": {
                        "type": "string"
                    },
                    "requestId": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    }
                },
                "type": "object"
            },
            "rest.Status": {
                "enum": [
                    "SUCCESS",
                    "ERROR"
                ],
                "example": "SUCCESS",
                "type": "string",
                "x-enum-varnames": [
                    "StatusSuccess",
                    "StatusError"
                ]
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/actions/{id}": {
            "delete": {
                "description": "Deletes an existing building action.",
                "parameters": [
                    {
                        "description": "Action id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete building action",
                "tags": [
                    "actions"
                ]
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Returns service health based on database connectivity.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Service Unavailable"
                    }
                },
                "summary": "Health check",
                "tags": [
                    "healthcheck"
                ]
            }
        },
        "/planets": {
            "get": {
                "description": "Returns planets, optionally filtered by player id.",
                "parameters": [
                    {
                        "description": "Player id (UUID)",
                        "in": "query",
                        "name": "player",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-array_communication_PlanetDtoResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List planets",
                "tags": [
                    "planets"
                ]
            },
            "post": {
                "description": "Creates a planet from the provided payload.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/communication.PlanetDtoRequest",
                                        "summary": "request",
                                        "description": "Planet payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Planet payload",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-communication_PlanetDtoResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create planet",
                "tags": [
                    "planets"
                ]
            }
        },
        "/planets/{id}": {
            "delete": {
                "description": "Deletes a planet by id.",
                "parameters": [
                    {
                        "description": "Planet id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete planet",
                "tags": [
                    "planets"
                ]
            },
            "get": {
                "description": "Returns a planet and all related game data.",
                "parameters": [
                    {
                        "description": "Planet id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-communication_FullPlanetDtoResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get planet",
                "tags": [
                    "planets"
                ]
            }
        },
        "/planets/{id}/actions": {
            "post": {
                "description": "Creates a building action for the planet provided in path parameter. The planet field in the body is ignored and replaced with this path value.",
                "parameters": [
                    {
                        "description": "Planet id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/communication.BuildingActionDtoRequest",
                                        "summary": "request",
                                        "description": "Building action payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Building action payload",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-communication_BuildingActionDtoResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Conflict"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create building action",
                "tags": [
                    "actions"
                ]
            }
        },
        "/players": {
            "get": {
                "description": "Returns players, optionally filtered by api_user.",
                "parameters": [
                    {
                        "description": "API user id (UUID)",
                        "in": "query",
                        "name": "api_user",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-array_communication_PlayerDtoResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List players",
                "tags": [
                    "players"
                ]
            }
        },
        "/players/{id}": {
            "delete": {
                "description": "Deletes a player by id.",
                "parameters": [
                    {
                        "description": "Player id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete player",
                "tags": [
                    "players"
                ]
            },
            "get": {
                "description": "Returns a player by id.",
                "parameters": [
                    {
                        "description": "Player id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-communication_PlayerDtoResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get player",
                "tags": [
                    "players"
                ]
            }
        },
        "/universes": {
            "get": {
                "description": "Returns all universes.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-array_communication_UniverseDtoResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List universes",
                "tags": [
                    "universes"
                ]
            }
        },
        "/universes/{id}": {
            "delete": {
                "description": "Deletes a universe by id.",
                "parameters": [
                    {
                        "description": "Universe id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete universe",
                "tags": [
                    "universes"
                ]
            },
            "get": {
                "description": "Returns a universe and related resources/buildings.",
                "parameters": [
                    {
                        "description": "Universe id (UUID)",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "format": "uuid",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-communication_FullUniverseDtoResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get universe",
                "tags": [
                    "universes"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "description": "Base path for the galactic-sovereign API",
            "url": "/v1"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Galactic Sovereign API",
	Description:      "REST API for the Galactic Sovereign backend service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
