// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actions/{id}": {
            "delete": {
                "description": "Deletes an existing building action.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Delete building action",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Action id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Returns service health based on database connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/planets": {
            "get": {
                "description": "Returns planets, optionally filtered by player id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "List planets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player id (UUID)",
                        "name": "player",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-array_communication_PlanetDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a planet from the provided payload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "Create planet",
                "parameters": [
                    {
                        "description": "Planet payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/communication.PlanetDtoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_PlanetDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/planets/{id}": {
            "get": {
                "description": "Returns a planet and all related game data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "Get planet",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Planet id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_FullPlanetDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a planet by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planets"
                ],
                "summary": "Delete planet",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Planet id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/planets/{id}/actions": {
            "post": {
                "description": "Creates a building action for the planet provided in path parameter. The planet field in the body is ignored and replaced with this path value.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Create building action",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Planet id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Building action payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/communication.BuildingActionDtoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_BuildingActionDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/players": {
            "get": {
                "description": "Returns players, optionally filtered by api_user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "List players",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API user id (UUID)",
                        "name": "api_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-array_communication_PlayerDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/players/{id}": {
            "get": {
                "description": "Returns a player by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Get player",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Player id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_PlayerDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a player by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Delete player",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Player id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/universes": {
            "get": {
                "description": "Returns all universes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universes"
                ],
                "summary": "List universes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-array_communication_UniverseDtoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/universes/{id}": {
            "get": {
                "description": "Returns a universe and related resources/buildings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universes"
                ],
                "summary": "Get universe",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Universe id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_FullUniverseDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a universe by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universes"
                ],
                "summary": "Delete universe",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Universe id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "communication.BuildingActionDtoRequest": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string",
                    "format": "uuid"
                },
                "planet": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.BuildingActionDtoResponse": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string",
                    "format": "uuid"
                },
                "completedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "currentLevel": {
                    "type": "integer"
                },
                "desiredLevel": {
                    "type": "integer"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "planet": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.BuildingCostDtoResponse": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string",
                    "format": "uuid"
                },
                "cost": {
                    "type": "integer"
                },
                "progress": {
                    "type": "number"
                },
                "resource": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.BuildingResourceProductionDtoResponse": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "integer"
                },
                "building": {
                    "type": "string",
                    "format": "uuid"
                },
                "progress": {
                    "type": "number"
                },
                "resource": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.BuildingResourceStorageDtoResponse": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "integer"
                },
                "building": {
                    "type": "string",
                    "format": "uuid"
                },
                "progress": {
                    "type": "number"
                },
                "resource": {
                    "type": "string",
                    "format": "uuid"
                },
                "scale": {
                    "type": "number"
                }
            }
        },
        "communication.FullBuildingDtoResponse": {
            "type": "object",
            "properties": {
                "costs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.BuildingCostDtoResponse"
                    }
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "productions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.BuildingResourceProductionDtoResponse"
                    }
                },
                "storages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.BuildingResourceStorageDtoResponse"
                    }
                }
            }
        },
        "communication.FullPlanetDtoResponse": {
            "type": "object",
            "properties": {
                "buildingActions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.BuildingActionDtoResponse"
                    }
                },
                "buildings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.PlanetBuildingDtoResponse"
                    }
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "homeworld": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "player": {
                    "type": "string",
                    "format": "uuid"
                },
                "productions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.PlanetResourceProductionDtoResponse"
                    }
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.PlanetResourceDtoResponse"
                    }
                },
                "storages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.PlanetResourceStorageDtoResponse"
                    }
                }
            }
        },
        "communication.FullUniverseDtoResponse": {
            "type": "object",
            "properties": {
                "buildings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.FullBuildingDtoResponse"
                    }
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.ResourceDtoResponse"
                    }
                }
            }
        },
        "communication.PlanetBuildingDtoResponse": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string",
                    "format": "uuid"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "level": {
                    "type": "integer"
                },
                "planet": {
                    "type": "string",
                    "format": "uuid"
                },
                "updatedAt": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "communication.PlanetDtoRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "player": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.PlanetDtoResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "homeworld": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "player": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.PlanetResourceDtoResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "planet": {
                    "type": "string",
                    "format": "uuid"
                },
                "resource": {
                    "type": "string",
                    "format": "uuid"
                },
                "updatedAt": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "communication.PlanetResourceProductionDtoResponse": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string",
                    "format": "uuid"
                },
                "planet": {
                    "type": "string",
                    "format": "uuid"
                },
                "production": {
                    "type": "integer"
                },
                "resource": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.PlanetResourceStorageDtoResponse": {
            "type": "object",
            "properties": {
                "planet": {
                    "type": "string",
                    "format": "uuid"
                },
                "resource": {
                    "type": "string",
                    "format": "uuid"
                },
                "storage": {
                    "type": "integer"
                }
            }
        },
        "communication.PlayerDtoRequest": {
            "type": "object",
            "properties": {
                "api_user": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "universe": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.PlayerDtoResponse": {
            "type": "object",
            "properties": {
                "api_user": {
                    "type": "string",
                    "format": "uuid"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "universe": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "communication.ResourceDtoResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "communication.UniverseDtoRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "communication.UniverseDtoResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "rest.ResponseEnvelope-array_communication_PlanetDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.PlanetDtoResponse"
                    }
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-array_communication_PlayerDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.PlayerDtoResponse"
                    }
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-array_communication_UniverseDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/communication.UniverseDtoResponse"
                    }
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_BuildingActionDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.BuildingActionDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_FullPlanetDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.FullPlanetDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_FullUniverseDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.FullUniverseDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_PlanetDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.PlanetDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_PlayerDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.PlayerDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_UniverseDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.UniverseDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-string": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.Status": {
            "type": "string",
            "enum": [
                "SUCCESS",
                "ERROR"
            ],
            "x-enum-varnames": [
                "StatusSuccess",
                "StatusError"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1/galactic-sovereign",
	Schemes:          []string{},
	Title:            "Galactic Sovereign API",
	Description:      "REST API for the Galactic Sovereign backend service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
