name: Build frontend

on:
  push:
    paths:
      - "website/user-dashboard/**"
      - "website/stellar-dominion/**"
      - ".github/workflows/build-frontend.yml"
      - ".github/workflows/services*.yml"
      - ".github/workflows/user-dashboard*.yml"
      - ".github/workflows/stellar-dominion*.yml"
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
      - "!.github/workflows/stellar-dominion-service*.yml"

jobs:
  # https://github.com/dorny/paths-filter
  detect-code-changes:
    runs-on: ubuntu-latest
    outputs:
      user-dashboard: ${{ steps.filter.outputs.user-dashboard }}
      stellar-dominion: ${{ steps.filter.outputs.stellar-dominion }}
      ci: ${{ steps.filter.outputs.ci }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref_name }}
          # https://github.com/dorny/paths-filter?tab=readme-ov-file#conditional-execution
          filters: |
            user-dashboard:
              - 'website/user-dashboard/**'
            stellar-dominion:
              - 'website/stellar-dominion/**'
            ci:
              - '.github/workflows/**'
  analyze-code-changes:
    runs-on: ubuntu-latest
    needs: [detect-code-changes]
    outputs:
      user-dashboard: ${{ steps.user-dashboard.outputs.rebuild }}
      stellar-dominion: ${{ steps.stellar-dominion.outputs.rebuild }}
      persist-tags: ${{ steps.persist-tags.outputs.status }}
    steps:
      - name: user-dashboard rebuild status
        id: user-dashboard
        run: echo 'rebuild=${{ needs.detect-code-changes.outputs.user-dashboard == 'true' || needs.detect-code-changes.outputs.ci == 'true' }}' >> $GITHUB_OUTPUT
      - name: stellar-dominion rebuild status
        id: stellar-dominion
        run: echo 'rebuild=${{ needs.detect-code-changes.outputs.stellar-dominion == 'true' || needs.detect-code-changes.outputs.ci == 'true' }}' >> $GITHUB_OUTPUT
      - name: stellar-dominion rebuild status
        id: persist-tags
        run: echo 'status=${{ needs.detect-code-changes.outputs.user-dashboard == 'true' || needs.detect-code-changes.outputs.stellar-dominion == 'true' || needs.detect-code-changes.outputs.ci == 'true' }}' >> $GITHUB_OUTPUT
  build-user-dashboard:
    needs: [analyze-code-changes]
    if: ${{ needs.analyze-code-changes.outputs.user-dashboard == 'true' }}
    uses: ./.github/workflows/user-dashboard-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-stellar-dominion:
    needs: [analyze-code-changes]
    if: ${{ needs.analyze-code-changes.outputs.stellar-dominion == 'true' }}
    uses: ./.github/workflows/stellar-dominion-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  persist-service-tags:
    runs-on: ubuntu-latest
    needs: [analyze-code-changes, build-user-dashboard, build-stellar-dominion]
    # https://github.com/actions/runner/issues/491
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Save user-dashboard tag
        if: ${{ needs.analyze-code-changes.outputs.user-dashboard == 'true' }}
        run: echo "${{ needs.build-user-dashboard.outputs.service-tag }}" > ./build/user-dashboard/version.txt
      - name: Save stellar-dominion tag
        if: ${{ needs.analyze-code-changes.outputs.stellar-dominion == 'true' }}
        run: echo "${{ needs.build-stellar-dominion.outputs.service-tag }}" > ./build/stellar-dominion/version.txt
      - name: Commit changes
        if: ${{ github.ref == 'refs/heads/master' && needs.analyze-code-changes.outputs.persist-tags == 'true' }}
        run: |
          git pull
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "infra: Bumped frontend versions to latest revision"
          git push
