name: Build and deploy services

on:
  push:
    paths:
      - ".github/workflows/**"
      - "deployments/**"
      - "pkg/**"
      - "internal/**"
      - "cmd/**"
      - "website/user-dashboard/**"
      - "website/stellar-dominion/**"
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
      - "!build/user-service/version.txt"
      - "!build/user-dashboard/version.txt"
      - "!build/stellar-dominion/version.txt"
      - "!build/stellar-dominion-service/version.txt"

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-concurrency-groups
concurrency:
  group: master-deployment
  cancel-in-progress: true

jobs:
  # https://github.com/dorny/paths-filter
  detect-code-changes:
    runs-on: ubuntu-latest
    outputs:
      ci: ${{ steps.filter.outputs.ci }}
      deployment: ${{ steps.filter.outputs.deployment }}
      user-service: ${{ steps.filter.outputs.user-service }}
      stellar-dominion-service: ${{ steps.filter.outputs.stellar-dominion-service }}
      user-dashboard: ${{ steps.filter.outputs.user-dashboard }}
      stellar-dominion: ${{ steps.filter.outputs.stellar-dominion }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref_name }}
          # https://github.com/dorny/paths-filter?tab=readme-ov-file#conditional-execution
          filters: |
            ci:
              - '.github/workflows/**'
            deployment:
              - "deployments/**"
            user-service:
              - "pkg/**"
              - "internal/**"
              - "cmd/users/**"
            stellar-dominion-service:
              - "pkg/**"
              - "internal/**"
              - "cmd/stellar-dominion/**"
            user-dashboard:
              - 'website/user-dashboard/**'
            stellar-dominion:
              - 'website/stellar-dominion/**'
  analyze-code-changes:
    runs-on: ubuntu-latest
    needs: [detect-code-changes]
    outputs:
      user-service: ${{ steps.user-service.outputs.rebuild }}
      stellar-dominion-service: ${{ steps.stellar-dominion-service.outputs.rebuild }}
      user-dashboard: ${{ steps.user-dashboard.outputs.rebuild }}
      stellar-dominion: ${{ steps.stellar-dominion.outputs.rebuild }}
    steps:
      - name: Determine user-service rebuild status
        id: user-service
        run: |
          echo 'rebuild=${{ needs.detect-code-changes.outputs.user-service == 'true' || needs.detect-code-changes.outputs.ci == 'true' }}' >> $GITHUB_OUTPUT
      - name: Determine stellar-dominion-service rebuild status
        id: stellar-dominion-service
        run: |
          echo 'rebuild=${{ needs.detect-code-changes.outputs.stellar-dominion-service == 'true' || needs.detect-code-changes.outputs.ci == 'true' }}' >> $GITHUB_OUTPUT
      - name: Determine user-dashboard rebuild status
        id: user-dashboard
        run: |
          echo 'rebuild=${{ needs.detect-code-changes.outputs.user-dashboard == 'true' || needs.detect-code-changes.outputs.ci == 'true' }}' >> $GITHUB_OUTPUT
      - name: Determine stellar-dominion rebuild status
        id: stellar-dominion
        run: |
          echo 'rebuild=${{ needs.detect-code-changes.outputs.stellar-dominion == 'true' || needs.detect-code-changes.outputs.ci == 'true' }}' >> $GITHUB_OUTPUT
  analyze-persist-tags-status:
    runs-on: ubuntu-latest
    needs: [detect-code-changes, analyze-code-changes]
    outputs:
      persist: ${{ steps.persist-tags.outputs.persist }}
    steps:
      - name: Detect if service tags should be persisted
        id: persist-tags
        run: |
          echo 'persist=${{ needs.analyze-code-changes.outputs.user-service == 'true' || needs.analyze-code-changes.outputs.stellar-dominion-service == 'true' || needs.analyze-code-changes.outputs.user-dashboard == 'true' || needs.analyze-code-changes.outputs.stellar-dominion == 'true' }}' >> $GITHUB_OUTPUT
  analyze-deploy-status:
    runs-on: ubuntu-latest
    needs: [detect-code-changes, analyze-persist-tags-status]
    outputs:
      deploy-services: ${{ steps.deploy-services.outputs.deploy }}
    steps:
      - name: Detect if services should be deployed
        id: deploy-services
        run: |
          echo 'deploy=${{ (github.ref == 'refs/heads/master') && (needs.analyze-persist-tags-status.outputs.persist == 'true' || needs.detect-code-changes.outputs.deployment == 'true') }}' >> $GITHUB_OUTPUT

  tests:
    runs-on: ubuntu-latest
    needs: [analyze-code-changes]
    if: ${{ needs.analyze-code-changes.outputs.user-service == 'true' || needs.analyze-code-changes.outputs.stellar-dominion-service == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Run tests with coverage
        run: go test ./... -coverpkg=./... -race -covermode=atomic -coverprofile=coverage.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
  build-user-service:
    needs: [tests]
    uses: ./.github/workflows/user-service-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-stellar-dominion-service:
    needs: [tests]
    uses: ./.github/workflows/stellar-dominion-service-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-dashboard:
    needs: [analyze-code-changes]
    if: ${{ needs.analyze-code-changes.outputs.user-dashboard == 'true' }}
    uses: ./.github/workflows/user-dashboard-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-stellar-dominion:
    needs: [analyze-code-changes]
    if: ${{ needs.analyze-code-changes.outputs.stellar-dominion == 'true' }}
    uses: ./.github/workflows/stellar-dominion-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  backup-deployment-config:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs:
      [
        analyze-deploy-status,
        build-user-service,
        build-stellar-dominion-service,
        build-user-dashboard,
        build-stellar-dominion,
      ]
    if: ${{ needs.analyze-deploy-status.outputs.deploy-services == 'true' }}
    steps:
      - name: Back-up deployment config
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          script: |
            rm -rf ~/deployments.bak
            mv ~/deployments ~/deployments.bak
            mkdir ~/deployments
  sync-deployment-configuration:
    runs-on: ubuntu-latest
    needs:
      [
        backup-deployment-config,
        analyze-code-changes,
        build-user-service,
        build-stellar-dominion-service,
        build-user-dashboard,
        build-stellar-dominion,
      ]
    steps:
      - uses: actions/checkout@v4
      - name: Substitute acme email
        run: |
          mv deployments/traefik-template.yml deployments/traefik.yml
          sed -i 's/${EMAIL_TO_BE_REPLACED}/${{ secrets.ACME_EMAIL }}/g' deployments/traefik.yml
      - name: Configure docker-compose deployment
        # https://deploy-preview-13474--docsdocker.netlify.app/compose/env-file/#compose-2x
        run: |
          echo "ENV_USER_DATABASE_PASSWORD=${{ secrets.USER_DATABASE_MANAGER_PASSWORD }}" >> ./deployments/.env
          echo "ENV_STELLAR_DOMINION_DATABASE_PASSWORD=${{ secrets.STELLAR_DOMINION_DATABASE_MANAGER_PASSWORD }}" >> ./deployments/.env
          echo "USER_DASHBOARD_ORIGIN=${{ secrets.USER_DASHBOARD_ORIGIN }}" >> ./deployments/.env
          echo "STELLAR_DOMINION_ORIGIN=${{ secrets.STELLAR_DOMINION_ORIGIN }}" >> ./deployments/.env
          echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}" >> ./deployments/.env
          echo "TRAEFIK_USER=${{ secrets.TRAEFIK_USER }}" >> ./deployments/.env
          echo "TRAEFIK_HASHED_PASSWORD='"'${{ secrets.TRAEFIK_HASHED_PASSWORD }}'"'" >> ./deployments/.env
      - name: Configure user-service tag from workflow output
        if: ${{ needs.analyze-code-changes.outputs.user-service == 'true' }}
        run: |
          echo "USER_SERVICE_TAG=${{ needs.build-user-service.outputs.service-tag }}" >> ./deployments/.env
      - name: Configure user-service tag from existing tag
        if: ${{ needs.analyze-code-changes.outputs.user-service == 'false' }}
        run: |
          echo "USER_SERVICE_TAG=$(cat ./build/user-service/version.txt)" >> ./deployments/.env
      - name: Configure stellar-dominion-service tag from workflow output
        if: ${{ needs.analyze-code-changes.outputs.stellar-dominion-service == 'true' }}
        run: |
          echo "STELLAR_DOMINION_SERVICE_TAG=${{ needs.build-stellar-dominion-service.outputs.service-tag }}" >> ./deployments/.env
      - name: Configure stellar-dominion-service tag from existing tag
        if: ${{ needs.analyze-code-changes.outputs.stellar-dominion-service == 'false' }}
        run: |
          echo "STELLAR_DOMINION_SERVICE_TAG=$(cat ./build/stellar-dominion-service/version.txt)" >> ./deployments/.env
      - name: Configure user-dashboard tag from workflow output
        if: ${{ needs.analyze-code-changes.outputs.user-dashboard == 'true' }}
        run: |
          echo "USER_DASHBOARD_TAG=${{ needs.build-user-dashboard.outputs.service-tag }}" >> ./deployments/.env
      - name: Configure user-dashboard tag from existing tag
        if: ${{ needs.analyze-code-changes.outputs.user-dashboard == 'false' }}
        run: |
          echo "USER_DASHBOARD_TAG=$(cat ./build/user-dashboard/version.txt)" >> ./deployments/.env
      - name: Configure stellar-dominion tag from workflow output
        if: ${{ needs.analyze-code-changes.outputs.stellar-dominion == 'true' }}
        run: |
          echo "STELLAR_DOMINION_TAG=${{ needs.build-stellar-dominion.outputs.service-tag }}" >> ./deployments/.env
      - name: Configure stellar-dominion tag from existing tag
        if: ${{ needs.analyze-code-changes.outputs.stellar-dominion == 'false' }}
        run: |
          echo "STELLAR_DOMINION_TAG=$(cat ./build/stellar-dominion/version.txt)" >> ./deployments/.env
      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_DEPLOY_SSH_KNOWN_HOSTS }}
      - name: Sync deployment configuration
        # https://www.tecmint.com/rsync-local-remote-file-synchronization-commands/#3_Copy_a_Directory_from_Local_to_Remote_Server
        run: |
          rsync -avzh ./deployments ubuntu@${{ secrets.EC2_DEPLOY_HOST }}:/home/ubuntu//
  deploy:
    runs-on: ubuntu-latest
    needs: [sync-deployment-configuration]
    steps:
      - name: Deploy latest services version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          script: |
            docker compose -f ./deployments/compose.yaml up -d
  clean-deployment-config-backup:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Clean back-up of deployment config
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          script: |
            rm -rf ~/deployments.bak

  persist-service-tags:
    runs-on: ubuntu-latest
    needs:
      [
        analyze-code-changes,
        analyze-persist-tags-status,
        build-user-service,
        build-stellar-dominion-service,
        build-user-dashboard,
        build-stellar-dominion,
        clean-deployment-config-backup,
      ]
    # https://github.com/actions/runner/issues/491
    if: |
      always() &&
      ${{ !contains(needs.*.result, 'failure') }} &&
      ${{ !contains(needs.*.result, 'cancelled') }} &&
      github.ref == 'refs/heads/master' && 
      needs.analyze-persist-tags-status.outputs.persist == 'true'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Save user-service tag
        if: ${{ needs.analyze-code-changes.outputs.user-service == 'true' }}
        run: |
          echo "${{ needs.build-user-service.outputs.service-tag }}" > ./build/user-service/version.txt
      - name: Save stellar-dominion-service tag
        if: ${{ needs.analyze-code-changes.outputs.stellar-dominion-service == 'true' }}
        run: |
          echo "${{ needs.build-stellar-dominion.outputs.service-tag }}" > ./build/stellar-dominion-service/version.txt
      - name: Save user-dashboard tag
        if: ${{ needs.analyze-code-changes.outputs.user-dashboard == 'true' }}
        run: |
          echo "${{ needs.build-user-dashboard.outputs.service-tag }}" > ./build/user-dashboard/version.txt
      - name: Save stellar-dominion tag
        if: ${{ needs.analyze-code-changes.outputs.stellar-dominion == 'true' }}
        run: |
          echo "${{ needs.build-stellar-dominion.outputs.service-tag }}" > ./build/stellar-dominion/version.txt
      - name: Commit changes
        run: |
          git pull
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "infra: Bumped services versions to latest revision"
          git push
