name: Build services

on:
  push:
    paths:
      - "cmd/users/**"
      - "cmd/stellar-dominion/**"
      - "pkg/**"
      - "internal/**"
      - ".github/workflows/build-services.yml"
      - ".github/workflows/services*.yml"
      - ".github/workflows/user-service*.yml"
      - ".github/workflows/stellar-dominion-service*.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Run tests with coverage
        run: go test ./... -coverpkg=./... -race -covermode=atomic -coverprofile=coverage.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
  build-user-service:
    needs: [tests]
    uses: ./.github/workflows/user-service-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-stellar-dominion-service:
    needs: [tests]
    uses: ./.github/workflows/stellar-dominion-service-build-and-push.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  persist-service-tags:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [build-user-service, build-stellar-dominion-service]
    # https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Save user-service tag
        run: echo "${{ needs.build-user-service.outputs.service-tag }}" > ./build/user-service/version.txt
      - name: Save stellar-dominion-service tag
        run: echo "${{ needs.build-stellar-dominion-service.outputs.service-tag }}" > ./build/stellar-dominion-service/version.txt
      - name: Commit changes
        run: |
          git pull
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "infra: Bumped services versions to latest revision"
          git push
