name: Deploy service

on:
  push:
    paths:
      - "build/users/version.txt"
      - "build/webserver/version.txt"
      - ".github/workflows/deploy-services.yml"
  # # https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows:
      [
        "Build and push user-service docker image",
        "Build and push webserver docker image",
      ]
    types:
      - completed
    branches: [master]

jobs:
  collect-services-versions:
    runs-on: ubuntu-latest
    outputs:
      user-service-tag: ${{ steps.user-service.outputs.tag }}
      webserver-tag: ${{ steps.webserver.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract user service tag
        id: user-service
        run: echo "tag=$(cat ./build/users/version.txt)" >> $GITHUB_OUTPUT
      - name: Extract webserver tag
        id: webserver
        run: echo "tag=$(cat ./build/webserver/version.txt)" >> $GITHUB_OUTPUT
  backup-deployment-config:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: [collect-services-versions]
    steps:
      - name: Back-up deployment config
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          script: |
            cp -r ~/deployments ~/deployments.bak
  verify-ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      - name: ssh
        run: |
          ssh ubuntur@${{ secrete.EC2_DEPLOY_HOST }} "ls deployments"
      - name: display
        run: cat ~/.ssh/known_hosts
  sync-deployment-configuration:
    runs-on: ubuntu-latest
    needs: [backup-deployment-config, collect-services-versions]
    steps:
      - uses: actions/checkout@v4
      - name: Configure docker-compose deployment
        run: |
          echo "USER_SERVICE_TAG=${{ needs.collect-services-versions.outputs.user-service-tag }}" >> ./deployments/.env
          echo "ENV_DATABASE_PASSWORD=${{ secrets.DATABASE_MANAGER_PASSWORD }}" >> ./deployments/.env
          echo "WEBSERVER_TAG=${{ needs.collect-services-versions.outputs.webserver-tag }}" >> ./deployments/.env
          echo "WEBSERVER_ORIGIN=${{ secrets.DOMAIN_NAME }}" >> ./deployments/.env
          echo "API_HOST=${{ secrets.DOMAIN_NAME }}/api" >> ./deployments/.env
          echo "WEBSERVER_HOST=${{ secrets.DOMAIN_NAME }}" >> ./deployments/.env
          echo "TRAEFIK_HOST=${{ secrets.DOMAIN_NAME }}/traefik" >> ./deployments/.env
      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_DEPLOY_SSH_KNOWN_HOSTS }}
      - name: Sync deployment configuration
        # https://www.tecmint.com/rsync-local-remote-file-synchronization-commands/#3_Copy_a_Directory_from_Local_to_Remote_Server
        run: |
          rsync -avzh ./deployments ubuntu@${{ secrets.EC2_DEPLOY_HOST }}:/home/ubuntu//
  deploy:
    runs-on: ubuntu-latest
    needs: [sync-deployment-configuration]
    steps:
      - name: Back-up deployment config
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          script: |
            docker compose -f ./deployments/compose.yaml up -d
  clean-deployment-config-backup:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Clean back-up of deployment config
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          script: |
            rm -rf ~/deployments.bak
