name: Deploy service

on:
  push:
    paths:
      - "build/users/version.txt"
      - "build/webserver/version.txt"
      - ".github/workflows/deploy-services.yml"

jobs:
  collect-services-versions:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      user-service-tag: ${{ steps.user-service.outputs.tag }}
      webserver-tag: ${{ steps.webserver.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract user service tag
        id: user-service
        run: echo "tag=$(cat ./build/users/version.txt)" >> $GITHUB_OUTPUT
      - name: Extract webserver tag
        id: webserver
        run: echo "tag=$(cat ./build/webserver/version.txt)" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: [collect-services-versions]
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_DEPLOY_SSH_KNOWN_HOSTS }}
      - name: Update running docker instance
        # https://github.com/docker/compose/issues/10309
        # https://stackoverflow.com/questions/39168239/update-only-one-container-via-docker-compose
        run: |
          echo "USER_SERVICE_TAG=${{ needs.collect-services-versions.outputs.user-service-tag }}" >> ./deployments/.env
          echo "WEBSERVER_TAG=${{ needs.collect-services-versions.outputs.webserver-tag }}" >> ./deployments/.env
          echo "ENV_DATABASE_PASSWORD=${{ secrets.DATABASE_MANAGER_PASSWORD }}" >> ./deployments/.env
          echo "DEPLOY_HOST=${{ secrets.EC2_DEPLOY_HOST }}"
          echo "WEBSERVER_ORIGIN=http://dashboard.${{ secrets.EC2_DEPLOY_HOST }}"
          docker \
            --host ssh://ubuntu@${{ secrets.EC2_DEPLOY_HOST }} \
            compose \
            -f ./deployments/compose.yaml \
            up \
            -d
