name: Build and push docker image
on:
  workflow_call:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
    # https://stackoverflow.com/questions/74062838/send-parameter-into-custom-github-action
    inputs:
      docker-file:
        required: true
        type: string
      docker-image-name:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
      - name: Extract commit hash
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.docker-file }}
          build-args: GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}
          push: true
          tags: totocorpsoftwareinc/${{ inputs.docker-image-name }}:${{ env.GIT_COMMIT_HASH }}
