name: Build docker image
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
      - name: Extract commit hash
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/users/Dockerfile
          build-args: GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}
          push: true
          tags: totocorpsoftwareinc/user-service:${{ env.GIT_COMMIT_HASH }}
