name: Build and deploy user-service

on:
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
    paths:
      - "cmd/**"
      - "pkg/**"
      - "internal/**"
      - "build/users/**"
      - ".github/workflows/user-service*.yml"

env:
  DOCKER_NETWORK_BRIDGE_NAME: "totocorp-network"
  DATABASE_PORT: 5432
  SERVER_PORT: 80
  RETRIES_COUNT: 5

jobs:
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  tests:
    # https://github.com/orgs/community/discussions/74772
    if: ${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }}
    uses: ./.github/workflows/tests.yml
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build-docker-image:
    if: ${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }}
    # https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot
    needs: [tests]
    permissions:
      contents: write
    uses: ./.github/workflows/user-service-build-and-push-docker-image.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: [build-docker-image]
    # https://medium.com/ryanjang-devnotes/ci-cd-hands-on-github-actions-docker-hub-aws-ec2-ba09f80297e1
    steps:
      - name: Extract commit hash
        run: echo "GIT_COMMIT_HASH=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Inject database password
        run: echo "ENV_DATABASE_PASSWORD=${{ secrets.DATABASE_MANAGER_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Update running docker instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          # https://github.com/appleboy/ssh-action
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.EC2_DEPLOY_SSH_KEY_PASSPHRASE }}
          # For docker stop and rm steps:
          # https://stackoverflow.com/questions/69943233/print-only-names-column-from-docker-container-ls-la-output
          # https://stackoverflow.com/questions/74800773/how-to-avoid-getting-an-error-message-when-there-is-no-docker-container-image-vo
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sudo docker pull totocorpsoftwareinc/user-service:${{ env.GIT_COMMIT_HASH }}
            sudo docker container ls -la --format "{{.Names}}" | grep user-service | xargs --no-run-if-empty sudo docker stop user-service
            sudo docker container ls -la --format "{{.Names}}" | grep user-service | xargs --no-run-if-empty sudo docker rm user-service
            sudo docker run \
              --network ${{ env.DOCKER_NETWORK_BRIDGE_NAME }} \
              -p ${{ env.DATABASE_PORT}} \
              -p ${{ env.SERVER_PORT}}:${{ env.SERVER_PORT}} \
              -e ENV_DATABASE_PASSWORD='${{ env.ENV_DATABASE_PASSWORD }}' \
              --name user-service \
              -d \
              --restart on-failure:${{ env.RETRIES_COUNT}} \
              totocorpsoftwareinc/user-service:${{ env.GIT_COMMIT_HASH }}
  persist-service-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: [deploy]
    steps:
      - name: Save service tag
        run: echo "${{ env.GIT_COMMIT_HASH }}" > ./build/users/version.txt
      - name: Commit changes
        run: |
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "infra: Bumped user service version to ${{ env.GIT_COMMIT_HASH }}"
          git push
