name: user-service

on:
  workflow_call:
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-outputs-from-a-reusable-workflow
    outputs:
      service-tag:
        description: "Tag of the generated service docker image"
        value: ${{ jobs.extract-service-tag.outputs.version }}
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
    paths:
      - "build/user-service/Dockerfile"

jobs:
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  extract-service-tag:
    uses: ./.github/workflows/services-extract-tag.yml
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: [extract-service-tag]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/user-service/Dockerfile
          build-args: GIT_COMMIT_HASH=${{ needs.extract-service-tag.outputs.version }}
          push: true
          tags: totocorpsoftwareinc/user-service:${{ needs.extract-service-tag.outputs.version }}
