name: Build and deploy webserver

on:
  push:
    paths:
      - "website/**"
      - "build/webserver/**"
      - ".github/workflows/webserver*.yml"

env:
  DOCKER_NETWORK_BRIDGE_NAME: "totocorp-network"
  NODE_PORT: 3001
  RETRIES_COUNT: 5

jobs:
  build-docker-image:
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    permissions:
      contents: write
    uses: ./.github/workflows/webserver-build-and-push-docker-image.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      webserver-host: ${{ secrets.EC2_DEPLOY_HOST }}
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    needs: [build-docker-image]
    steps:
      - name: Extract commit hash
        run: echo "GIT_COMMIT_HASH=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)" >> $GITHUB_ENV
      - name: Update running docker instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.EC2_DEPLOY_SSH_KEY_PASSPHRASE }}
          # https://docs.docker.com/reference/cli/docker/login/#password-stdin
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sudo docker pull totocorpsoftwareinc/webserver:${{ env.GIT_COMMIT_HASH }}
            sudo docker container ls -la --format "{{.Names}}" | grep webserver | xargs --no-run-if-empty sudo docker stop webserver
            sudo docker container ls -la --format "{{.Names}}" | grep webserver | xargs --no-run-if-empty sudo docker rm webserver
            sudo docker run \
              --network ${{ env.DOCKER_NETWORK_BRIDGE_NAME }} \
              -p ${NODE_PORT}:${NODE_PORT} \
              --name webserver \
              -d \
              --restart on-failure:${{ env.RETRIES_COUNT}} \
              totocorpsoftwareinc/webserver:${{ env.GIT_COMMIT_HASH }}
  persist-service-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: [deploy]
    steps:
      - name: Save service tag
        run: echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7 > ./build/webserver/version.txt
      - name: Commit changes
        run: |
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "infra: Bumped webserver version to ${{ env.GIT_COMMIT_HASH }}"
          git push
