name: Build and deploy webserver

on:
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
    paths:
      - 'webserver/**'
      - 'build/**'
      - '.github/**'

env:
  EC2_HOST: "35.180.67.147"
  DOCKER_NETWORK_BRIDGE_NAME: "totocorp-network"
  NODE_PORT: 3001
  RETRIES_COUNT: 5

jobs:
  build-docker-image:
    uses: ./.github/workflows/user-service-push-docker-image.yml
    secrets:
      docker-file: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    inputs:
        package-name: ./build/webserver/Dockerfile
        docker-image-name: webserver
  deploy:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Extract commit hash
        run: echo "GIT_COMMIT_HASH=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Inject database password
        run: echo "ENV_DATABASE_PASSWORD=${{ secrets.DATABASE_MANAGER_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Update running docker instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ env.EC2_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.EC2_DEPLOY_SSH_KEY_PASSPHRASE }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker pull totocorpsoftwareinc/webserver:${{ env.GIT_COMMIT_HASH }}
            sudo docker container ls -la --format "{{.Names}}" | grep webserver | xargs --no-run-if-empty sudo docker stop webserver
            sudo docker container ls -la --format "{{.Names}}" | grep webserver | xargs --no-run-if-empty sudo docker rm webserver
            sudo docker run \
              --network ${{ env.DOCKER_NETWORK_BRIDGE_NAME }} \
              -p ${NODE_PORT}:${NODE_PORT} \
              --name webserver \
              -d \
              --restart on-failure:${{ env.RETRIES_COUNT}} \
              totocorpsoftwareinc/webserver:${{ env.GIT_COMMIT_HASH }}
