name: Build and deploy webserver

on:
  push:
    paths:
      - "website/**"
      - "build/webserver/**"
      - ".github/workflows/webserver*.yml"

env:
  DOCKER_NETWORK_BRIDGE_NAME: "totocorp-network"
  NODE_PORT: 3001
  RETRIES_COUNT: 5

jobs:
  build-docker-image:
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    permissions:
      contents: write
    uses: ./.github/workflows/webserver-build-and-push-docker-image.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      webserver-host: ${{ secrets.EC2_DEPLOY_HOST }}
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v4
      - name: Extract user service tag
        run: echo "USER_SERVICE_TAG=$(cat ./build/users/version.txt)" >> $GITHUB_ENV
      - name: Extract webserver tag
        run: echo "WEBSERVER_TAG=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Create docker compose env file
        env:
          USER_SERVICE_TAG: ${{ env.USER_SERVICE_TAG }}
          WEBSERVER_TAG: ${{ env.WEBSERVER_TAG }}
          ENV_DATABASE_PASSWORD: ${{ secrets.DATABASE_MANAGER_PASSWORD }}
        run: |
          echo "USER_SERVICE_TAG=${{ env.USER_SERVICE_TAG }}" >> ./deployments/.env
          echo "WEBSERVER_TAG=${{ env.WEBSERVER_TAG }}" >> ./deployments/.env
          echo "ENV_DATABASE_PASSWORD=${{ secrets.DATABASE_MANAGER_PASSWORD }}" >> ./deployments/.env
      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_DEPLOY_SSH_KNOWN_HOSTS }}
      - name: Update running docker instance
        run: |
          docker \
            --host ssh://ubuntu@${{ secrets.EC2_DEPLOY_HOST }} \
            compose \
            -f ./deployments/compose.yaml \
            up \
            -d
  persist-service-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && (${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }})
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: [deploy]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Save service tag
        env:
          WEBSERVER_TAG: ${{ env.WEBSERVER_TAG }}
        run: echo "${{ env.WEBSERVER_TAG }}" > ./build/webserver/version.txt
      - name: Commit changes
        env:
          WEBSERVER_TAG: ${{ env.WEBSERVER_TAG }}
        run: |
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "infra: Bumped webserver version to ${{ env.WEBSERVER_TAG }}"
          git push
