name: Build and deploy webserver

on:
  push:
    paths:
      - "website/**"
      - "build/webserver/**"
      - ".github/workflows/webserver*.yml"

env:
  DOCKER_NETWORK_BRIDGE_NAME: "totocorp-network"
  NODE_PORT: 3001
  RETRIES_COUNT: 5

jobs:
  build-docker-image:
    uses: ./.github/workflows/webserver-build-and-push-docker-image.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      webserver-host: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Extract commit hash
        run: echo "GIT_COMMIT_HASH=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Inject database password
        run: echo "ENV_DATABASE_PASSWORD=${{ secrets.DATABASE_MANAGER_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Update running docker instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.EC2_DEPLOY_HOST }}"
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.EC2_DEPLOY_SSH_KEY_PASSPHRASE }}
          # https://docs.docker.com/reference/cli/docker/login/#password-stdin
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sudo docker pull totocorpsoftwareinc/webserver:${{ env.GIT_COMMIT_HASH }}
            sudo docker container ls -la --format "{{.Names}}" | grep webserver | xargs --no-run-if-empty sudo docker stop webserver
            sudo docker container ls -la --format "{{.Names}}" | grep webserver | xargs --no-run-if-empty sudo docker rm webserver
            sudo docker run \
              --network ${{ env.DOCKER_NETWORK_BRIDGE_NAME }} \
              -p ${NODE_PORT}:${NODE_PORT} \
              --name webserver \
              -d \
              --restart on-failure:${{ env.RETRIES_COUNT}} \
              totocorpsoftwareinc/webserver:${{ env.GIT_COMMIT_HASH }}
